### ISSUE TITLE
Meldung Testtaker ValidFrom irreführend

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#105]
Wird eine Anmeldung vor der eingestellten Zeit in **ValidFrom** versucht erscheint die folgende Meldung:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/a347ae47-3667-45ba-b601-d40fd129aae4)

**Comment by tobhu1981** [comment]
Wird eine Anmeldung vor der eingestellten Zeit in **ValidFrom** versucht erscheint die folgende Meldung:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/a347ae47-3667-45ba-b601-d40fd129aae4)

**Comment by paflov** [comment]
Ein Bug ist, das nicht und schon gar kein neuer. Aber zugegebenermaßen verbesserungswürdig. Was sollte deiner Meinung nach da stehen?

**Comment by tobhu1981** [comment]
Ne ein Bug ist das wirlich nicht. Hmm...vielleicht sowas wie "Login noch nicht freigegeben.." oder so.
