### ISSUE TITLE
Fehler Speicherung mehrere Logs

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#107]
@tobhu1981 commented on [Thu Jun 23 2022](https://github.com/iqb-berlin/testcenter-frontend/issues/406)

---

@tobhu1981 commented on [Thu Jun 23 2022](https://github.com/iqb-berlin/testcenter-frontend/issues/406#issuecomment-1164153089)

IQB-Testcenter version 12.1.9@12.4.2

Meldung aus BW: Sollen Logs aus mehreren Testungen gemeinsam gespeichert werden kommt es zu einem Fehler in der Logdatei. Dort steht dann folgendes drin: 
```xml
<br />
<b>Fatal error</b>: Maximum execution time of 30 seconds exceeded in <b>/var/www/html/classes/helper/CSV.class.php</b> on line <b>96</b><br />
```
Bei der Speicherung einzelnen Logs tritt der Fehler nicht auf.

---

@jkoelm commented on [Tue Jun 28 2022](https://github.com/iqb-berlin/testcenter-frontend/issues/406#issuecomment-1168743913)

Bei uns tritt genau das auch auf, wenn man nur die Logs einer einzelnen Testung runterladen will. Bei mehreren Testgruppen ist das, was in der ausgegebenen csv steht, ein bisschen anders: 

```
> <br />
> <b>Fatal error</b>:  Allowed memory size of 134217728 bytes   exhausted (tried to allocate 4096 bytes) in   <b>/var/www/html/classes/dao/DAO.class.php</b> on line   <b>68</b><br />
```

---

@jkoelm commented on [Fri Jul 01 2022](https://github.com/iqb-berlin/testcenter-frontend/issues/406#issuecomment-1172305794)

Eine Konkretisierung: Am 02.06. funktionierte es noch normal, danach kam ein Update, an dem es wohl liegt, ab 08.06. geht es nicht mehr.

---

@tobhu1981 commented on [Wed Sep 14 2022](https://github.com/iqb-berlin/testcenter-frontend/issues/406#issuecomment-1246424238)

Nach wie vor scheint hier ein Problem vorzuliegen, auch beim Laden eines einzelnen Files.

**Comment by tobhu1981** [comment]
Update: Jenny hat mir einen Bereich im Produktivsystem (12.1.11@12.4.4) genannt in dem es aktuell nicht möglich ist die Logs herunterzuladen: **Englisch Präpilotierung 2022 (19)** Ich habe dich dafür mal freigegeben. Wie ich diese Datenmenge jetzt im Testcenter Testversion erzeugen soll, weiß ich leider nicht. Daher kann ich es in IQB-Testcenter Version 13.0.0-alpha grad nicht testen.

**Comment by paflov** [comment]
Hier bestehen zwei Probleme:
1. Das Erstellen der CSV dauert wegen einem Programmierfehler absurd lange.
- Habe ich behoben in TC13-alpha2. 
- Weil es so ein trivialer Fix war, habe ich ihn auch als Hotfix im Produktivsystem eingebracht. Dort können also - zumindest Gruppenweise - jetzt Logs heruntergeladen werden.

2. Die CSV-Datei wird zwischendurch in den Hauptspeicher geladen, dann läuft dieser voll, wenn es sehr viele Daten sind.

#113

**Comment by tobhu1981** [comment]
Was genau ist mit Gruppenweise gemeint? 5, 10 oder mehr auf einmal? Habe gerade mal in der Studie: Englisch Präpilotierung 2022 (19) versucht alle dort vorhandenen Logs mit einmal herunterzuladen, sind 15 Dateien. Das ging leider nicht. Dann habe ich mal geschaut bis zu welcher Anzahl es geht. Es geht bis zur 13. Datei, da sind wir dann bei einer Größe von knapp 39MB. Alles was darüber ist scheint nicht zu gehen.

**Comment by paflov** [comment]
Mit Gruppenweise meine jede Gruppe einzeln. Mehrere zusammen sind immer noch zu groß, ja...

**Comment by tobhu1981** [comment]
Ich nehme mal an ich soll auf das mit der 13alpha testen oder? Hast du irgendeine Idee wie ich da Probedaten rein bekomme (Logs) ohne riesige Pseudotestungen durchführen zu müssen?

**Comment by paflov** [comment]
Wenn es im Produktivsystem soweit OK ist, reicht mir das auch. Habe ja den selben Code der Produktiv-Instanz als Hotfix eingebracht.

Ein Script um große Mengen an Beispieldaten zu erzeugen / einzuspielen, wäre vermutlich ohnehin mal nützlich, oder? Ich mache mir darüber mal Gedanken.

Das Ticket mache ich mal zu, das wichtigste ist ja gefixed: die Leute kommen an ihre Logs.
