### ISSUE TITLE
SystemCheck: Anzeige Auflösung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#114]

**Comment by tobhu1981** [comment]
Ist vielleicht erst einmal nicht so wichtig, aber ich soll ja alles auflisten was ich so finden:
Die unter allgemeine Informationen angezeigte Bildschrimauflösung stimmt nicht. Mein Bildschirm hat eine Auflösung 1920x1080 pxl. Der Bereich des Fensters im Browser hat 1920x930 pxl. Der SystemCheck gibt 1760x990 pxl an.

**Comment by tobhu1981** [comment]
Update: Hmm...bei der 2.Durchführung des SC wird es richtig angezeigt. Kann es nicht mehr reproduzieren.

**Comment by paflov** [comment]
Tja, wenn es nicht zu reproduzieren ist...

**Comment by tobhu1981** [comment]
Tja.....dann ist das wohl so. ich werde es bei Gelegenheit nochmal testen.
