### ISSUE TITLE
SystemCheck: Report wird nicht gelöscht, bevor ein neuer SysCheck gestartet wurde

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#116]
Boah....wie erklär ich das. Ich weiß auch gar nicht ob dies so ein realistisches Szenario wäre. Na egal ich erklär mal. Es gibt 2 Arbeitsbereiche: SystemCheck1 und SystemCheck2. Dort habe ich 2 unterschiedliche SystemCheck-Xml reingelegt. Hintergrund könnte sein, es gibt zwei geplante Testungen mit unterschiedlichen Anforderungen an die IT. Die Testverantwortlichen wollen also vielleicht beide Ansprüche an die Tests auf einem PC abprüfen.
Hier die Config von **SystemCheck1**-Xml:

```xml
<Config unit="UnitSC1" savekey="123">
		<UploadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="10000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">100000, 200000, 400000, 800000</UploadSpeed>
		<DownloadSpeed min="9999999" good="2048" maxDevianceBytesPerSecond="200000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">400000, 800000, 1600000, 3200000</DownloadSpeed>		
		<Q id="1" type="header" prompt="Fragebogen zum Systemcheck 1"></Q>
		<Q id="2" type="radio" prompt="1. Überprüfung Optionsfeld (Wähle Optionen und merke dir diese.)">1#2#3</Q>
		<Q id="2a" type="text" prompt="2. Überprüfung Text (Trage hier etwas ein und merke es dir.)"/>
		<Q id="3" type="string" prompt="3. Überprüfung String (Trage hier etwas ein und merke es dir.)"/>
		<Q id="4" type="check" prompt="4.Überprüfung Check (setze einmal den Haken)">Hier wurde ein Haken gesetzt.</Q>
	</Config>
```

Hier die Config der **SystemCheck2-xml**:

```xml
<Config unit="UnitSC2" savekey="123">
		<UploadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="10000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">100000, 200000, 400000, 800000</UploadSpeed>
		<DownloadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="200000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">400000, 800000, 1600000, 3200000</DownloadSpeed>		
		<Q id="1" type="header" prompt="Abschnitt I: Hier musst du nichts eingeben!"></Q>
	</Config>
```
Ich melde mich ab und starte den Systemcheck1. Am Ende wird mir der Bericht richtig angezeigt.
Dann gehe ich zurück zur Anmeldeseite und starte den SystemCheck2. Auch hier läuft alles normal, nur die Berichtseite hat offentsichtlich die Einträge bzgl. Fragebogen aus dem SystemCheck1 noch drin stehen. Im SystemCheck2 ist ja nur eine Frage angelegt. Es scheint als würden diese Stelle im Bereicht nicht aktualisiert. Die falsch angezeigten Fragen werden auch in der SystemCheck2.csv abgespeichert. 

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/735c035e-5e34-4357-b7c2-f83e8d306442)

Drücke ich F5 bevor ich den SystemCheck2 starte sieht die Berichtsseite richtig aus.

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/b90e4036-4d5d-4d3e-87a9-f146c34148e0)

Oh Mann...hoffe du verstehtst wsa ich meine.

**Comment by tobhu1981** [comment]
Boah....wie erklär ich das. Es gibt 2 Arbeitsbereiche: SystemCheck1 und SystemCheck2. Dort habe ich 2 unterschiedliche SystemCheck-Xml reingelegt. Hier die Config von SystemCheck1-Xml:

<Config unit="UnitSC1" savekey="123">
		<UploadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="10000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">100000, 200000, 400000, 800000</UploadSpeed>
		<DownloadSpeed min="9999999" good="2048" maxDevianceBytesPerSecond="200000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">400000, 800000, 1600000, 3200000</DownloadSpeed>		
		<Q id="1" type="header" prompt="Fragebogen zum Systemcheck 1"></Q>
		<Q id="2" type="radio" prompt="1. Überprüfung Optionsfeld (Wähle Optionen und merke dir diese.)">1#2#3</Q>
		<Q id="2a" type="text" prompt="2. Überprüfung Text (Trage hier etwas ein und merke es dir.)"/>
		<Q id="3" type="string" prompt="3. Überprüfung String (Trage hier etwas ein und merke es dir.)"/>
		<Q id="4" type="check" prompt="4.Überprüfung Check (setze einmal den Haken)">Hier wurde ein Haken gesetzt.</Q>
	</Config>

**Comment by paflov** [comment]
Ja verstehe ich. Der report müsste gelöscht werden, bevor man einen neuen Check startet.
