### ISSUE TITLE
TLK: Geht offline wenn Antwortdaten eines Tests gelöscht werden

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#122]

**Comment by tobhu1981** [comment]
Hier bin ich mir nicht sicher was hier genau passiert:
Eine TLK auf **PC A** ist geöffnet und ein Test läuft bspw. auf einem **PC B**. Ich melde mich als Testperson auf **PC B** ab und melde mich als Admin an. Dann wechsle ich in den AB des Tests und lösche die dort angelegten Antworten/Ergebnisse für diesen Test. Sobal dich das mache, wechselt die Live-Anzeige in der TLK auf PC A von grün auf rot (offline). Es erscheint außerdem eine Fehlermeldung: Warnung: Für diese Funktion haben Sie keine Berechtigung. .........403 Forbidden.

**Comment by paflov** [comment]
Bedenke, dass das Löschen von Ergebnisdaten auch das Löschen der Sessions mit sich zieht. Durch dieses Akt wird die Studie endgültig beendet. Das wäre vielleicht mal in Frage zu stellen, ist aber das definierte Verhalten seit Testcenter 1.

Rot wird die Anzeige, weil beim Löschen von logins der Broadcasting-Service "geflashed" wird (damit dort keine sessions verbleiben die es nicht mehr gibt).

Der Gruppen-Monitor Account wird mitgelöscht, daher hat er plötzlich keine Berechtigung mehr.

Ich würde sagen das ist alles korrektes Verhalten.
