### ISSUE TITLE
TLK: Springe zu Block: Funzt manchmal nicht

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#123]
Irgendwie klappt das manchmal nicht. TLK ist auf einem PC A geöffnet auf PC B ist eine Testperson angemeldet und befindet sich im Test. Der angezeigte Status und auch die Position im Test werden von der TLK richtig angezeigt, sie scheint also richtig verbunden zu sein. Wenn ich nun nur diese Person in TLK auswähle und einen Block markiere und "springe zu" wähle, klappt das manchmal nicht. In einem Fall hatte ich es ein paar mal probiert, aber die TP wurde nicht weitergeleitet, es ist nichts im Test passiert. Dann habe ich mal auf PC B mittels F5 den Test neu geladen. Beim Laden ist er dann mehrfach zwischen den Blöcken hin und her gesprungen, wie als wenn jetzt erst die Signale für die Sprünge ankommen würden.

**Comment by tobhu1981** [comment]
Irgendwie klappt das manchmal nicht. TLK ist auf einem PC A geöffnet auf PC B ist eine Testperson angemeldet und befindet sich im Test. Der angezeigte Status und auch die Position im Test werden von der TLK richtig angezeigt, sie scheint also richtig verbunden zu sein. Wenn ich nun nur diese Person in TLK auswähle und einen Block markiere und "springe zu" wähle, klappt das manchmal nicht. In einem Fall hatte ich es ein paar mal probiert, aber die TP wurde nicht weitergeleitet, es ist nichts im Test passiert. Dann habe ich mal auf PC B mittels F5 den Test neu geladen. Beim Laden ist er dann mehrfach zwischen den Blöcken hin und her gesprungen, wie als wenn jetzt erst die Signale für die Sprünge ankommen würden.

**Comment by paflov** [comment]
Tja, wie soll ich das reproduzieren.
Muss man beobachten.
