### ISSUE TITLE
TLK: Sperrung Block bei Sprung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#124]
Ich kann via TLK zwischen zeitbeschränkten Blöcken springen wie ich will, die Blöcke werden derzeitig nicht gesperrt

**Comment by tobhu1981** [comment]
Ich kann via TLK zwischen zeitbeschränkten Blöcken springen wie ich will, die Blöcke werden derzeitig nicht gesperrt

**Comment by paflov** [comment]
Sollte eigentlich nicht möglich sein, siehe #83. 
Doch ein neuer Bug?!

**Comment by tobhu1981** [comment]
Hoffe wir reden da nicht aneinander vorbei. Jenny spricht von Blöcken deren Zeit bereits abgelaufen ist und die dann via TLK als gesperrt markiert werden sollen. Aktuell ist es so: Wird ein zeitbeschränkter Block mittels Navimenu verlassen und die Meldung bzgl. verlassen eines zeitbeschränkten Bereichs bestätigt oder die Zeit des Blocks ist abgelaufen, wird der Block gesperrt und man kann auch mittels TLK nicht mehr in den Block navigieren. 
Ich hatte dich gestern aber so verstanden, dass sobald mittels TLK (unabhängig ob Zeit schon abgelaufen ist) zu einem anderen Block gesprungen wird, der aktuelle Block gesperrt wird und man in diesen nicht zurückkehren kann. Wenn ich dich da richtig verstanden habe, würde das aktuell nicht gehen, man kann immer wieder in den Block zurückkehren, wenn die Zeit noch nicht abgelaufen ist.

**Comment by paflov** [comment]
Stimmt das sind zwei verschiedene Dinge.
ich paraphrasiere mal das Problem hier:
*Was passiert wenn ein GM einen Teilnehmer aus aus einem Zeitgesteuerten Block entfernt. Soll der Block gesperrt werden, oder nur die Zeit angehalten werden?*

Ich werde das dahingehend ändern, dass die zeitgesteuerte Block beim verlassen - auch durch GM-Befehl - gesperrt werden. Ich hoffe, das ist auch wirklich das gewünschte Verhalten...

**Comment by tobhu1981** [comment]
Hier ist was ganz schräg. Zum einen werden mit den Daten in AB: Testung Controller keine Antwortdaten geschrieben obwohl ich mich mit K1bTP4 in einem Hot-Modus anmelde, außerdem wird immer gleich der erste Block gesperrt, obwohl ich noch nicht drin war. Auch die Anzeige der TLK ist seltsam, manchmal werden alle Personen der Group: Klasse1b angezeigt, manchmal nur das Booklet der angemeldeten Person. Das sollten wir noch einmal gemeinsam am Montag testen.

**Comment by paflov** [comment]
Aktuell nicht reproduzierbar.
