### ISSUE TITLE
TLK: Test pausieren kann umgangen werden

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#128]
Ich hatte eine Testung mit eingeschaltetem Unit-Menu laufen und habe dann mittels TLK pausiert. Es kam dann auch die Meldung, dass der Test pausiert ist. Wenn ich dann aber mittels Unit-Menu den Test beende und das Booklet erneut aufrufe, wird der Test forgesetzt und die Pausierung wird aufgehoben. Hier müsste vielleicht grundsätzlich entschieden werden, ob der Test während der Pause mittels Unit-Menu beendet werden kann.

**Comment by tobhu1981** [comment]
Verhalten ist unverändert.

**Comment by paflov** [comment]
@jojohoch Sorry Sorry!!! ich hab die Tickets aus versehen dir statt Tobias zugeordnet! Ihr braucht mal Avatare ;)

**Comment by tobhu1981** [comment]
Kann ich grad nicht sicher prüfen, weil jetzt sowieso immer diese Meldung (..."wurde kurz angehalten") kommt, wenn man ein Booklet fortsetzen möchte.

**Comment by tobhu1981** [comment]
funzt
