### ISSUE TITLE
TLK: Test entsperren

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#129]

**Comment by tobhu1981** [comment]
Wird eine Testung via TLK beendet, wird auf Testerseite der Test beendet und zur Bookletauswahl gewechselt. Das Booklet ist dann grau (inaktiv) hinterlegt und es steht "gesperrt" darin. Wenn nun in der TLK die Testung entsperrt wird, wird auf Testpersonseite die Seite offensichtlich nicht aktualisiert, das Booklet bleibt inaktiv. Erst nachdem die Seite neu geladen wurde (F5), ist das Booklet wieder aktiv und kann ausgewählt werden.

**Comment by paflov** [comment]
Ja, das ist technisch nicht zu vermeiden. In der TLk erscheint sogar irgendwo ein Hnweis daraus, dass der Teilnehmer neuladen muss...
