### ISSUE TITLE
Modus Review/Demo: Nach Zeitablauf kein Hinweis bzgl. Pflichtfeldern

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#138]

**Comment by tobhu1981** [comment]
Ich richte im Review-Modus eine zeitliche Beschränkung ein. Ich spiele den Test ab und befinde  mich in einer Aufgabe mit Pflichtfeldern. Ich mache nichts und lasse die Zeit verstreichen. Nach Ablauf der Zeit blättere ich zur nächsten Unit. Es kommt an dieser Stelle kein Hinweis, dass hier normalerweise nicht weiter geblättert werden könnte, weil noch nicht alles ausgefüllt wurde. Der Hinweis kommt nur wenn man vor Ablauf der Zeit weiterblättert. Ist jetzt wahrscheinlich nicht so mega wichtig.

**Comment by paflov** [comment]
naja, *nach* Ablauf der Zeit kann man ja auch weiterblättern. Genaugenommen wird man sogar weiter geblättert.
