### ISSUE TITLE
Neue Inhalte Unit-Xml werden nicht akzeptiert

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#146]
Das neue Studio erzeugt eine Reihe von neuen Attributen und Elementen in der Unit-Xml.
Diese verhindern aktuell, dass die Unit in das Testcenter in der aktuellsten Version: 13alpha auf dem Testserver geladen werden kann.

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/b6e00891-c955-4a47-a8b6-4531974b6b22)

Es gibt jetzt bzgl. Aufgabenkodierung ein neues Elemente `BaseVariables`. Da müsstest du wahrscheinlich noch nachziehen oder?

Bzgl. des Attributs: LastChange in DefRef und Metadaten habe ich Martin schon gefragt, ob er da bei der Ausgabe was ändern muss im Studio oder ob das so bleiben soll und du müsstest anpassen.

**Comment by paflov** [comment]
Wird im nächsten (beta-)release behoben werden.

**Comment by tobhu1981** [comment]
funzt
