### ISSUE TITLE
Review/Demo: Zeit wird nicht angezeigt bei Wiederbetreten eines Blocks

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#149]
Ist unit_show_time_left= ON in den Modi: Demo und Review wird die Zeit bei Betreten des jeweiligen Blocks angezeigt. Verlasse ich den Block jedoch und kehre wieder zurück in den Block, ist die Zeit nicht mehr zu sehen (obwohl die Zeit noch nicht abgelaufen ist)

**Comment by huaning-yang** [comment]
Das sollte jetzt wieder korrekt angezeigt werden im demo und review mode.

Allerdings ist mir aufgegallen, dass der Timer immer wieder von neu anfängt wenn man in eine zeitbeschränkte Unit zurückkehrt. Im demo/review mode wahrscheinlich nicht so dramatisch, aber ist das gewolltes Verhalten @paflov ?

**Comment by paflov** [comment]
Nein, ich dachte dazu gäbe es auch ein Ticket, finde es aber gerade nicht. Das sollte so nicht sein. Könntest du eigentlich auch gleich bearbeiten.

Hintergrund ist dass im Demo und Review modus keine Daten ins Backend weggespeichert werden und werden sollen. Beim laden einer Unit kommtauch der momentane Zeit-Zustand vom backend normalerweise. Nur im Demo/Review Modus entfällt das halt. Daher muss die Zeit pro Testlet auch noch mal irgendwo lokal gespeichert werden, und in diesem Fall vorn dort geladen werden.
Ich muss jetzt leider los, aber morgen können wir gerne zoomen.
