### ISSUE TITLE
SystemCheck: Fragebogen: String- und Textlänge Anzeige

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#150]
Werde viele Zeichen im Fragebogen in Text- oder Stringfeldern eingegeben, werden diese nicht in der Vorschau umgebrochen.

**Bsp: Textfeld:**

```xml
<Q id="2a" type="text" prompt="Weitere Informationen zur Ansprechperson"/>
```
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/e98be3e0-1457-4bf7-8c71-43ab05f8f681)

**In der Vorschau:**
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/cf6aeef7-df4d-4c4a-bc5b-22b3520a79b7)

**Comment by rhenck** [comment]
Das ist doch wohl eindeutig nen Bug... :D
