### ISSUE TITLE
SystemCheck: Ideen Optimierung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#156]
Hier mal eine Idee wie der SC aus meiner Sicht langfristig gesehen optimiert werden könnte, natürlich nur wenn techn. überhaupt möglich. Ich weiß nicht wie ihr das seht, aber schön wäre doch, wenn am Ende des SC eine Meldung kommt, ob das System geeignet ist oder nicht. Dafür könnten bestimmte Eckdaten gesammelt werden und in Summe zu einer automatischen Auswertung führen:

**Internetspeed**
Hier könnten einfach MIndestanforderungen definiert werden. Nur wen diese erfüllt sind, gilt diese Prüfung als bestanden.

**Geräteinformationen**
Hier wird geprüft, ob die ermittelten Daten bestimmten Kriterien entsprechen, bspw. Browserversion nicht älter als die letzten 2 Versionen oder vielleicht einfacher: Nicht älter als Version xx.xx (da man ja sonst ermitteln müsste, welche Versionen es davor gab). Oder auch ob die Auflösung einer Mindestanforderung entspricht usw.. Natürlich müssten hier vorab noch mehr Erfahrungen gesammelt werden, ab welcher Version geht was mit welchem Browser und so. Wenn alles den Anforderungen entspricht, gilt auch diese Prüfung als bestanden.

**Aufgabenvoransicht**
Hier könnten bspw. verschiedene Aufgabenelemente aufgeführt sein. Diese können dann ausprobiert werden und es kann direkt bewertet werden, ob das Element macht was es soll oder nicht. 

Bsp:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/7db24b5e-97e3-4aa0-83ff-8995c9021597)

Die Antworten werden entsprechend gespeichert und nur wenn alles mit "Ja" beantwortet wurde, wird dieser Teil der Prüfung als bestanden erachtet. 

Nur wenn alle Teile bestanden sind, erscheint eine entsprechende Meldung am Ende des SC.

**Comment by paflov** [comment]
Laut MM weiterhin nicht gewünscht
