### ISSUE TITLE
[e2e] Netzwerk-Geschwindigkeits-Test überspringen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#157]
Die e2e-tests failen häufig oder brauchen ewig lange, weil der Netzwerk-Check einfach so lange braucht. Man sollte den lieber auslassen.

**Comment by rhenck** [comment]
E2E Tests laufen generell nicht. Daher Ticket invalide. Kann wieder aufgemacht werden, falls die wieder laufen und das immernoch ein Problem ist.

**Comment by paflov** [comment]
Naj, der Pullrequest, der sie wieder aktiviert klemmt gerade noch in der Pipeline... Ich mach das dann mit oder Tobias.
