### ISSUE TITLE
CSV Ansicht der Systemcheck-Berichte klären

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#158]
Android 9
Firefox, Chrome und Edge in Version: 106

Bei Verwendung von Firefox werden manche Geräteinformationen im Vergleich zu Chrome und Edge ausgelesen und manche nicht. Wird nur ein Bericht für alle 3 Browser gespeichert, verschieben sich auch die Spalten im Bericht. Ich habe mal versucht das grafisch darzustellen:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/1890f65b-2269-4be0-97c2-aefa63d19025)

Die eigentlichen Dateien befinden sich hier:

https://box.hu-berlin.de/f/18dc2c06a15f4b94854e/?dl=1

**Comment by paflov** [comment]
trägst du hier noch was ein?

**Comment by paflov** [comment]
Also, welche Informationen über ein Gerät zu Verfügung gestellt werden, hängt vom gerät, vom Browser und den individuellen Einstellungen ab. Offenbar hat FF Mobile für dieses Gerät keinen Herstelle bereitgestellt.

Beim Erzeugen der CSVs werden Spalten, für die es keinen Inhalt gibt, weggelassen. Das "Verschieben" hängt damit zusammen: Eine Spalte wird erst angehängt, wenn das erste Mal eine Zeile mit diesem Inhalt auftaucht.

Die Frage ist: Hältst du das für arg ungünstig? Sonst würde ich daran jetzt nichts ändern.

**Comment by tobhu1981** [comment]
Nö ist erst einmal okay.
