### ISSUE TITLE
[Definitions] Unit.xsd an Teststudio output anpassen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#161]
* <Value> enthält keinen string, sondern die element <value> und <label>
* Die Reihenfolge der Element auf <root>-ebene soll egal sein
* Der Regex for @format soll vereinfacht werden: alpahnumerische Zeichen (und - _ ) in beliebieger zahel, auch 0

**Comment by tobhu1981** [comment]
Weiß nicht genau was hier gemeint ist. Unit.xsd = Schemadefinition?

**Comment by paflov** [comment]
Ja, Ticket hatte aber eigentlich nichts mit dir zu tun^^
