### ISSUE TITLE
GeoGebra Element wird nicht dargestellt

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#167]
Weiß nicht wie da der Stand im Testcenter ist, wollte es aber trotzdem ansprechen: 
Im Studio wird ein eingebettetes Geogebra-Element in der Vorschau angezeigt.
Ich exportiere die Aufgabe samt Player und importiere diese in das Testcenter.
Dann starte ich einen Test, aber das Geogebra-lement wird hier nicht angezeigt.

**Comment by paflov** [comment]
Müsste gehen, wenn das GeoGebra-Package mit in den Workspace geladen wird.
Wäre wichtig noch mal zu sicherzustellen vor dem Release!

**Comment by tobhu1981** [comment]
Hier wird aktuell die zugehörige GeoGebra-Datei nicht vom Studio ausgegeben. Ist in Klärung mit Martin.

**Comment by jojohoch** [comment]
Ist GeoGebra auf dem Testcenter verfügbar?

**Comment by tobhu1981** [comment]
Ok Philipp werde ich mal probieren. Was genau meinst du mit Package? Hier mal was ich herunterladen könnte:

![grafik](https://user-images.githubusercontent.com/78656991/199658373-5d866560-d8e3-479a-9b84-ddc8507b72af.png)

**Comment by paflov** [comment]
Ja, bist du. Du musst nicht die GeoGebra-Aufgabe sondern GeoGebra selbst runterladen. Aber ehrlich gesagt weiß  ich das auch nicht genau, was in dem Paket drin sein muss und wie man es erstellt. Das können dir nur JH oder MM erklären (oder RH eventuell). 
Das GeoGebra-Paket muss im Studio aber vorliegen (allerdings an zentraler Stelle wie wir gestern gelernt haben, nicht Workspace bezogen wie im TC).

**Comment by tobhu1981** [comment]
funzt jetzt
