### ISSUE TITLE
List of possible replacements wird nicht generiert

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#170]
https://pages.cms.hu-berlin.de/iqb/testcenter/pages/custom-texts.html

**Comment by paflov** [comment]
Noch mal von Tobias:

Hallo Richard und Philipp,

nur am Rande und ich weiß es nervt übel:

Die Tabelle auf https://pages.cms.hu-berlin.de/iqb/testcenter/dist/custom-texts.html --> List of possible replacements
wird noch nicht richtig dargestellt. Diese wird zur Zeit über das Wiki verlinkt.

In der README im TC-Mono wird bei Customizable Labels in the UI noch einmal auf eine andere Seite: https://pages.cms.hu-berlin.de/iqb/testcenter/pages/custom-texts.html verlinkt.
Hier fehlt die Tabelle mit den möglichen Parametern komplett.

Wenn ihr mal Luft habt irgendwann.....nur das es nicht unter geht.

Gruß
