### ISSUE TITLE
Fehler in der Unit.Xsd

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter#172]
Datei
`/definitions/vo_Unit.xsd`

Zeile 63

Fehler: `VariableFormatValueExplicit` fehlt.

korrigieren zu

```
<xs:union memberTypes="VariableFormatValueExplicit VariableFormatValueOther"/>
```

**Comment by tobhu1981** [comment]
Musst du mir mal bei Gelegenheit erklären wie die Schemadefinition auf die jeweilige XML angewendet wird.

**Comment by mechtelm** [comment]
Dieser Teil der Definition wird nie manuell erzeugt oder editiert und ist erst relevant, wenn Erfassungen über Fotos/QR-Code laufen. Das Ticket selbst ist bereits gefixt.
