### ISSUE TITLE
Fehler beim Laden von Units mit Geogebra

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#189]
# Fehlerbeschreibung

- Was ist passiert?

Die Fehlermeldung sieht für mich so aus als ob der Inhalt der Geogebra Datei zu groß zum Speichern ist: 500 Internal Server Error // SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1 

![testtaker1](https://user-images.githubusercontent.com/446878/208450235-1b06885c-54a9-4364-b33b-38edd3793b98.gif)

https://www.iqb-studio.de/#/a/68/2148/preview

**Comment by paflov** [comment]
Kann es sein, dass es sich hierbei um einen Fix im STUDIO, nicht im Testcenter handelt? Im testcenter werden Units aus gutem Grund nicht in der DB gespeichert. Außerdem verweist der Link oben eine Instanz des STUDIOs.

**Comment by paflov** [comment]
Ach so sorry. Achmi hats mir erklärt. Es geht nicht um die Unitdefinition sondern die Antwortdaten.
