### ISSUE TITLE
Ansicht Unitnavigation bei vielen Units ungünstig

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#202]
Sind viele Units in einer Studie angelegt und sollen diese mittels Unitnavigation wählbar sein, sieht das irgendwie komisch aus:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/9f9deead-2ac3-4f00-8e56-c337403ed39f)

Außerdem wird, falls eingeschaltet, die Zeitanzeige bei zeitbegrenzten Blöcken überdeckt.

**Comment by paflov** [comment]
Ist ein Duplikat von https://github.com/iqb-berlin/testcenter/issues/90

Die einzig sinnvolle Lösung ist, es scrollbar zu machen. Das hatte ich bereits gebaut, wurde aber von JK und co abgelehnt. Damit sind wir hier an einem toten Punkt...
