### ISSUE TITLE
Richtiges Protokoll für BS auswählen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#204]
in der .env:
Die Variable BROADCAST_SERVICE_URI_SUBSCRIBE muss mit wss beginnen, wenn TLS = on, ansonsten mit ws.

Sowas, nur in funktionierend:
BROADCAST_SERVICE_URI_SUBSCRIBE={$TLS='on' ? 'wss' : 'ws'}://${HOSTNAME}/bs/public

**Comment by rhenck** [comment]
Verstehe nicht, was hier das Problem ist. Kannst du etwas mehr ausführen?

Der Installer und Updater ersetzen alle Vorkommen von "ws" mit "wss", wenn man TLS anschaltet.

**Comment by paflov** [comment]
Ach so, das macht der updater. Wurde halt von BW konsultiert, weil die BS-Verbindung fehlschlug, denn da war das natürlich nicht der Fall. 
Fällt also in die Kategorie: "was wenn die Leute unseren Updater nicht benutzen"

Dachte das man das eventuell direkt in der env lösen kann. Ansonsten müssen wir wohl wirklich mal eine Doku machen, was man beachten muss wenn man zwar docker, aber nicht unseren Updater verwendet :/

**Comment by paflov** [comment]
* Besser setzen wir im backend-entrypoint.sh die URIs auf basis TLS_ON
* Dann kann die https / http und wss /ws Ersetzung in der update.sh entfernt werden
* dazu sollte ein Schalter kommen BROADCASTING SERVICE AN/AUS, damit man ihn auch ausmachen kann. Default sollte an sein, damit der BS nicht plötzlich aus geht, wenn man das vergisst nachzutragen.
* patch mitliefern, der die env beim update anpasst?
