### ISSUE TITLE
Blättern in gesperrten Blöcken

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#205]
Ich muss mal ausholen, vielleicht gibt es hier auch gar keine Möglichkeit das abzufangen:
Mal angenommen es gibt einen zeitbeschränkten Block und danach folgende Units. Im Navigationsmenu sind nur die Pfeile für vor und zurück eingeschaltet, die Units dazwischen werden nicht angezeigt. Nachdem der zeitbeschränkte Block durchlaufen wurde, ist dieser gesperrt und man landet auf der nachfolgenden Unit nach dem Block. Jetzt könnte wer auf die Idee kommen mittels Pfeil: Zurück noch einmal in den zeitbeschränkten Block zu gelangen. Dann erscheint die Meldung, dass der Block gesperrt ist. Soweit so gut. Wenn derjenige jetzt aber mehrfach auf Zurück klickt, durchläuft er die Units des zeitbeschränkten Blocks trotzdem. Er kann das nur nicht mehr sehen, weil die Meldung, dass der Block gesperrt ist, die Ansicht verhindert. Da in Unitmenu keine Units angezeigt werden, sieht er auch nicht wo er sich aktuell befindet. Wenn er jetzt wieder auf vorwärts klickt, erscheint es merkwürdig, dass er nicht wieder auf der ursprünglichen Unit nach dem Block landet, sondern dass er nun mindestens so oft auf vorwärts, wie zuvor auf rückwärts klicken muss um in die ursrüngliche Unit zu gelangen. Lange Rede....kann man irgendwie verhindern, dass in gesperrten Blöcken trotzdem noch navigiert werden kann?

**Comment by paflov** [comment]
In einer sehr viel früheren Version des Testcenters (vor deiner Zeit), war das sogar schon. Wir haben davon Abstand genommen, weil es mehrere schwer auflösbare Szenarios mit sich führt:
* Was wenn ein Block (durch einen Monitor z. B.) wieder entsperrt wird?
* Was wenn die ID einer Unit in einem solchen gesperrten Block in die Adresszeile des Browsers eingegeben wird?
Ich glaube, es gab noch mehr.

Tatsächlich ist mir auch aufgefallen, dass man durch die Kombination bestimmter Booklet-Parameter so einen verwirrenden Zustand erreichen kann: Unit-Menü ausblenden (oder nur Pfeile halt) + Unit-Title Zeilee ausblenden. 

Hast du einen Vorschlag, wie man in dieser Situation deutlicher machen könnte, dass man sich bewegt?

**Comment by tobhu1981** [comment]
Wie wäre es, wenn man die gesperrte Unit noch im Hintergrund sehen kann, nur halt nicht mehr darauf zugreifen kann und immer die Meldung, dass der Block gesperrt ist darüber liegt? Keine Ahnung, vielleicht könnte man auch die gesperrte Unit etwas "unscharf" im Hintergrund anzeigen, falls das überhaupt geht. Hast du bestimmt auch schon mal gesehen...auf manchen Webseiten, Zeitungen oder so, sieht man Text im Hintergrund unscharf und darüber die Meldung, dass man bezahlen muss um alles zu sehen.

**Comment by paflov** [comment]
Möglich wärs aber ein ganz schöner Aufwand die extra zu laden nur um sie unscharf im Hintergrund zu halten.

**Comment by tobhu1981** [comment]
wohl wahr. Nur den Titel der Unit in der sich befindet mit in der Meldung bzgl. gesperrter Block?

**Comment by paflov** [comment]
Das Problem besteht ja nur, wenn der Booklet-Parameter `unit_title` auf “OFF” steht. ich würde sagen, man ändert es dahingehend, dass bei gesperrten Units die Titelzeile immer zu sehen ist, unabhängig vom Status von `unit_title`.

**Comment by tobhu1981** [comment]
Ja macht Sinn. Leider in dem aktuellen Testfall (Carola BiSS-Studie) sollen genau diese Titel im Speedtestblock nicht zu sehen sein. Aber ich würde sagen das ist ein Sonderfall und wird ja nun nicht ständig vorkommen.

**Comment by paflov** [comment]
Beschluss Stuhlkreis 9.5.23:
- betreten eines (z. B. über Url) gesperrten (Zeit/Freigabewort) Blockes führt immer zur ersten Unit
- In den Menüs dürfen nur Aufgaben anclickbar sein, die man auch betreten darf (also die jeweils 1. eines gesperrten Blocks)
- dies als Booklet-Paramater optional machen ?
