### ISSUE TITLE
 Testcenter Dokumentation: Tabelle CustomText-Parameter fehlerhaft

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#211]
Tabelle wird nicht richtig dargestellt: https://pages.cms.hu-berlin.de/iqb/testcenter/dist/custom-texts.html

**Comment by paflov** [comment]
Hattest du das nicht gefixed? Weiß du noch wie? Komische Sache.

**Comment by tobhu1981** [comment]
Ne..ich komm da gar nicht ran um was zu fixen. Kannst du mir vielleicht bei Gelegenheit mal zeigen. Wie wird denn diese Doku generiert?

**Comment by paflov** [comment]
Ach so das ging an Richard, dem ich das Ticket zugewiesen habe, weil ich glaube er hat sich damit schon mal geplagt :)

Hier, falls es dich dennoch interessiert:
https://github.com/iqb-berlin/testcenter/blob/21934a0989d85388d95ff275992fc84672afd599/scripts/create-docs.js#L141

**Comment by rhenck** [comment]
Weiß nicht genau warum das kaputt war, aktuell ist es wieder okay. Wird bei jedem Tag neu generiert und ich hatte ein paar Testtags angelegt. Dabei wird das wohl schiefgegangen sein. Kann mir aber nicht erklären warum, weil das auch bei meinen Tastags auf dem letzten Stand und damit okay gewesen sein sollte.
Müssen wir mal weiter im Auge behalten ob und wann das passiert.

**Comment by tobhu1981** [comment]
Ja komisch, hatte das Script bei mir mal lokal laufen plus custom-Text.md und custom-text.json. Hat alles schön generiert wie es sein soll.
