### ISSUE TITLE
TLK: Blocknavigation vor Freigabewort

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#214]
### TC-Version: 13.2.2

BW meldet: Ich bin als TLK angemeldet.
Ein SuS meldet sich zum Test an. Er bearbeitet einen Teil des Tests und kommt zu einem Block, wo ein Freigabewort verlangt wird. Anstatt das Freigabewort einzugeben, klickt der SuS ein paar Male auf weiter. In der TLK wird angezeigt, dass der SuS in dem entsprechenden Block voran gekommen ist - das sollte meiner Meinung nach nicht passieren.
Wenn der SuS endlich das Freigabewort eingibt, gelangt er nicht am Anfang des Blocks, sondern in der "Mitte" - je nachdem, wie oft er den weiter-Button angeklickt hatte.

Ihr könnt das selbst ansehen:
https://testcenter-test.lernstandserhebungen-bw.de
Account Lehrer: lehrer.m1 (ohne PW)
Account SuS: sus.m11 (ohne PW) oder sus.m12 oder sus.m13 …

**Comment by paflov** [comment]
Gehört ja eigentlich zu #205. Das ist das Navigationskonzept, auf das wir uns geeinigt hatten: Sperrung von Units bzw. Blocks heißt nicht, dass sie nicht betreten oder durchlaufen werden können, sondern nur, dass sie nicht angezeigt werden. So wie oben beschrieben, kann ich aber nachempfinden, dass das ungünstig sein kann.
Wäre mal zu klären, wie zum Beispiel JK und PK das sehen.

**Comment by tobhu1981** [comment]
Habe gerade mit Jenny drüber gesprochen. Welche Gründe es damals gab, dazu machte sie keine Äußerungen, nur dass sie das ähnlich wie BW sehen würde und es aus ihrer Sicht nicht so sein sollte.

**Comment by paflov** [comment]
Die Entscheidung von dieser Art der Navigation entschieden (also dass man gesperrte Blöcke und Units dennoch betreten kann), weil es einfacher zu implementieren ist und mit folgende Szenarien im Sinn:

- Was wenn ein Block (durch einen Monitor z. B.) wieder entsperrt wird?
- Was wenn die ID einer Unit in einem solchen gesperrten Block in die Adresszeile des Browsers eingegeben wird?
- Was, wenn es nach dem gesperrten Block keine betretbare Unit mehr gibt?
- Geschachtelte Blöcke...

Wenn man das ganze in einem Szenario mit Verzweigungen (adaptives Testen) worauf wir mit TBA II  ja zusteuern weiter denkt, wird es ziemlich kompliziert, zu sagen wo man hingeführt werden soll, wenn man sich auf einer gesperrten Units befindet. 
Wenn das wirklich ein Problem darstellt, müssen wir das diskutieren. Es ist allerdings ein gewaltiger Umbau, der dann fällig wäre...

**Comment by paflov** [comment]
Ich würde die weitere Diskussion darüber auf jeden Fall in die fernere Zukunft verlegen wollen, in der wir klarer sehen wie wir das adaptive testen realisieren.

**Comment by paflov** [comment]
Abgedeckt mir #205
