### ISSUE TITLE
Backend während initalisierungsvorgang sperren

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#217]
Das Backend sollte solange der Initialisierungsvorgang läuft nicht funktionieren. Sonst kommt es manchmal zu komischen Fehlern.

**Comment by mechtelm** [comment]
Kann doch über docker geregelt werden, dass also die traefik-route noch nicht gelegt wird, z. B. über
```
HEALTHCHECK CMD curl --fail http://localhost/health.php || exit 1 
```
oder so.
