### ISSUE TITLE
Beachten von Abhängigkeiten beim Löschen

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#223]
### 14.0.1
Ohne Berücksichtigung von Abhängigkeiten können die folgenden Dateien gelöscht werden:
* **voud** und **player** vor zugehöriger **xml**
* **booklet** vor zugehöriger **testtaker**

**Comment by paflov** [comment]
Problem tritt lokal nicht auf, aber nicht auf dem Testserver!
