### ISSUE TITLE
Bei Arbeitsbreichen letztes Änderungsdatum anzeigen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#227]
In der SuperAdmin-Ansicht der Arbeitsbereiche. Damit inaktive Arbeitsbereiche besser erkannt werden können.

**Comment by mechtelm** [comment]
Hm eigenlich Timestamp der Änderung, nicht die Änderung selbst.

**Comment by paflov** [comment]
In der Datenbanktabelle files gibt es ein Feld modification_ts. Das gibt die letzte Änderung an. Davon muss man wiederum das jüngste des workspaces heraussuchen, dann hat man das letzte Änderungsdatum des Workspaces. Dieses müsstest du im Endpunkt /workspaces (SystemController.calls.php Z. 18) mit zurück geben.

Bei Änderungen an Endpunkten ist zu beachten, die spec des Endpunktes mit zu ändern (in dem Fall zu finden in docs/api/system.spec.yml Z. 154. Ob alles dann passt erfährt man durch `make test-backend-api`. Kann sein dass auch Unit-Tests angepasst werden müssen (`make test-backned-unit`).

**Comment by huaning-yang** [comment]
Closed with #331.
