### ISSUE TITLE
Credentials im Localstorage nach Update machen Probleme

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#234]
Verbleiben Credentials im Localstorage kann das TC nach einem Update nicht richtig geladen werden.

**Comment by paflov** [comment]
Reproduzieren:
1. Ältere Testcenter Version installieren, z.B. 13.3.1 (https://pages.cms.hu-berlin.de/iqb/testcenter/pages/installation-prod.html)
2. Als Admin (?) Einloggen
3. Testcenter herunterfahren, updaten und neu starten
4. Login ist nicht mehr möglich, wenn man nicht die credentials aus dem Localstorage löscht

Das müsste doch eigentlich vermeidbar sein? Warum machen diese credentials probleme? Den account gibt es ja immer noch usw.

**Comment by huaning-yang** [comment]
Ich wollte das hier gerade testen, allerdings kann ich keine ältere Version mit dem install Skript installieren.
