### ISSUE TITLE
Upload von Testtakers: Namenskollisionen mit gelöschten Workspaces

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#235]
Steps:
- Vorhandener Workspace mit Testtakers
- Löschen des Workspaces
- Hochladen der gleichen Testtakers in neu erstellten Workspace

Fehler: Testtakers wird abgelehnt mit Hinweis auf bereits vorhandene Logins im anderen (eigentlich gelöschten) Workspace

**Comment by paflov** [comment]
Ich hatte genau diesen Fehler eigentlich schon mal in der 14.1.0 behoben. Vielleicht kommt nur dieser Fix nicht richtig an...
