### ISSUE TITLE
Selektoren ordentlich machen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#236]
Sowas ist nicht richtig:
selector: 'app-custom-text',

"app" sollte mit einem Anwendungskürzel ersetzt werden, um Namenskollisionen zu vermeiden.

**Comment by paflov** [comment]
Jap. Meiner Meinung braucht man eigentlich  gar kein prefix. Könnte man auf jeden Fall mal vereinheitlichen. Sollten wir vielleicht im Team besprechen oder?

**Comment by rhenck** [comment]
Wüsste nicht, wie das ohne Präfix gehen soll, wenn man Namenskollisionen vermeiden will.

**Comment by mechtelm** [comment]
Namenskollisionen entstehen nur mit importierten Komponenten. Ich würde sagen, dass alle unsere importierbaren Komponenten einer strikten Namenskonvention folgen, aber die Komponenten der Anwendung selbst keiner Konvention unterliegen.

**Comment by paflov** [comment]
Ich würde eigentlich sagen, das ist nur für Komponenten nötig, die tatsächlich zwischen Anwendungen geteilt werden sollen, und sowas haben wir ja seit der Abschaffung der IQB-Components gar nicht. Die Fälle, dass es innerhalb einer Anwendung zur Kollision kommt sind selten und irgendwie sehr theoretisch finde ich. Würde mich dem aber nicht entgegenstellen, wenn es dir wichtig ist.

**Comment by paflov** [comment]
Was war hier noch mal die Beschlusslage, nachdem wir drüber diskutiert hatten?

**Comment by huaning-yang** [comment]
@paflov: Sollen hier dann nur Selektoren angepasst werden die im Moment 'app' im selektor tragen oder auch Sachen wie 'alert', 'status-card' und 'unit-menu'? Also dann jeweils zu tc-alert, tc-status-card und tc-unit-menu

**Comment by rhenck** [comment]
> @paflov: Sollen hier dann nur Selektoren angepasst werden die im Moment 'app' im selektor tragen oder auch Sachen wie 'alert', 'status-card' und 'unit-menu'? Also dann jeweils zu tc-alert, tc-status-card und tc-unit-menu

Ich bin zwar nicht angesprochen, aber ja: alle.
