### ISSUE TITLE
Workspace-Admin: Multi-Upload von Dateien erlauben

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#245]
Edit: Siehe letzter Kommentar von Philipp, was genau zu tun ist.

Steps:
- Hochladen von Unit-XML und (gleichzeitig) zugehöriger VOUD

Erwartet:
- Beide Dateien werden angenommen

Tatsächlich:
- XML wird abgelehnt

![unitupload.png](https://images.zenhubusercontent.com/5f02f8ec6b89aad3f29e0502/cc58a2f7-512a-4ee7-91b1-bb5b4c9a775d)

**Comment by paflov** [comment]
Dies ist tatsächlich (ein schon sehr altes) Frontend-Problem. 

Die User umschiffen das seit eh und je in dem sie
a) die Dateien als ZIP hochladen
oder
b) erst alle Ressourcen auf einmal, dann alle unit, dann alle Booklets usw. laden und alles zusammen

Tatsächlich lassen sich auch beide zusammen hochladen, wenn man in der Dateiauswahl zuerst die Ressource anklickt, und dann die Unit.

Das Problem ist, dass die Upload-Komponente, wenn man mehrere Dateien auswählt getrennte Calls daraus macht. In dem Beispiel also einen für die Ressource und eine für die Unit. Und wenn erst die Unit ankommt, wird diese natürlich abgelehnt. Das war vor meiner Zeit, aber der Grund dafür war *glaube ich*, dass vor fünf Jahren Firefox noch keinen Multi-Upload konnte. Ich habe vor Jahren das Backend darauf vorbereitet, Multi-Upload nicht nur in ZIP-form anzunehmen, das das Frontend nie entsprechend umgebaut.

Todo: Die file-uplaoad Komponente so umbauen, dass sie mehrere Units/Files auf einmal mit einem Call hochschickt, und nicht für jeden einen Extra-Call.
