### ISSUE TITLE
Install Skript: Installation älterer Versionen schlägt fehl

### ISSUE THREAD

**Issue by huaning-yang** [iqb-berlin/testcenter#247]
Für ein anderes Ticket wollte ich eine ältere Version des Testcenters installieren um es dann upzudaten.
Bin dabei diesem Guide gefolgt: https://pages.cms.hu-berlin.de/iqb/testcenter/pages/installation-prod.html
Wenn ich install.sh ausführe und dann nicht die aktuellste Version installieren möchte(habe es mit 13.3.1, 13.1.0 und 14.2.0 probiert), dann schlägt das Skript immer an der gleichen Stelle fehl und zwar beim Download der tls-config.yml. Die Fehlermeldung lautet dann: 
https://raw.githubusercontent.com/iqb-berlin/testcenter/14.2.0/dist-src/tls-config.yml:
2023-03-07 16:51:55 ERROR 404: Not Found.

Im Install Skript ist es die Zeile 74.
Bei der aktuellsten Version(14.3.0) tritt dieses Problem nicht auf.
Könnt ihr das reproduzieren oder liegt es evtl doch an mir?

**Comment by rhenck** [comment]
Ja da ist ein grundsätzlicher Denkfehler drin. Das Skript ist immer das gleiche, aber die runterzuladenden Dateien ändern sich. Kann also so nicht klappen.

Da müsste man entweder das Skript anpassen, sodass das immer weiß welche Dateien für welche Version runterzuladen sind. Oder halt angepasste Install-Skripte für jede Version mit rausgeben.

Option A würde ich mal ausschließen, weil zu aufwändig und Fehleranfällig.
Option B ist in etwa das, was ich ursprünglich mal implementiert hatte, aber auf Wunsch von Martin und Sven wegmachen sollte. Jetzt haben wir den Salat. Weiß ich gerade nicht, wie das zu Lösen ist. Am besten mal im nächsten Dev-Treffen auf den Tisch bringen.

**Comment by paflov** [comment]
Ja, diese Frage müssen wir langsam klären.

Davon ab, @huaning-yang:
Wenn ich eine ältere Version installieren möchte, lade das install script von diesem Tag herunter und installiere damit, das müsste dann gehen.

**Comment by paflov** [comment]
Beschlusslage: Dazu nimmt man eben ältere Installer.

**Comment by rhenck** [comment]
Moment mal, als Lösung hierfür wäre doch aber zumindest eine Doku-Aktualisierung angesagt. Die ist afaik noch nicht da.

**Comment by rhenck** [comment]
Außerdem muss der Installer geändert werden, sodass er nicht vorgaukelt er könne ältere Versionen installieren.

**Comment by paflov** [comment]
Ja, stimmt.
