### ISSUE TITLE
Doku updaten

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#248]
Version wird nicht mehr in der docker-compose geführt, sondern in .env.

**Comment by paflov** [comment]
Welche Doku ist hier gemeint?

**Comment by rhenck** [comment]
https://pages.cms.hu-berlin.de/iqb/testcenter/pages/installation-prod.html

"Alternatively you may manually edit the file docker-compose.prod.yml. Find the lines starting with image and edit the version tag."
Das stimmt so nicht.
