### ISSUE TITLE
Unit-ID in allcaps bei Abruf der Workspace-Dateiliste

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#249]
Steps:
- Hochladen einer Unit-XML mit kleingeschriebenem Buchstaben in der ID (Bsp.: "abc")
- Abruf der Dateien im Workspace via Endpunkt: /workspace/{ws_id}/files

Erwartet: Die Unit lässt sich via ID in der Liste der Units finden
Tatsächlich: Die Unit-ID in der Liste ist in allcaps

**Comment by paflov** [comment]
Die ids sind nicht case sensitive.

**Comment by rhenck** [comment]
Warum - gibts da nen technischen Grund? Ist das irgendwo dokumentiert? Die API soll ja auch von extern benutzbar sein, und da sind solche Überraschungen ungünstig.

**Comment by paflov** [comment]
Auf welche Liste beziehst du dich dabei eigentlich?

**Comment by paflov** [comment]
Hat sich in TC 15 wo ohnehin Dateinamen und nicht mehr IDs für die Resourcen verwendet werden wohl erledigt.
