### ISSUE TITLE
Testheft starten nach Login?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter#259]

**Comment by mechtelm** [comment]
Wenn sich eine Testperson angemeldet hat und es nur ein Testheft gibt (99% der Fälle) - warum startet dieses Testheft nicht sofort? Die Seite selbst - also die Übersicht mit dem Start-Button - würde ich nicht entfernen, die ist wichtig als Sammelpunkt bei der Navigation, aber man sollte gleich nach der erfolgreichen Anmeldung und dem Laden der Booklet-Liste das erste starten, wenn nur eins gibt.

Wenn zwar etwas dagegen sprechen sollte für normale Testpersonen, dann sollte man dieses Verhalten wenigstens für Review- und Demo-Logins einrichten.

**Comment by paflov** [comment]
Spricht nichts dagegen. Also, immer, wenn es nur ein Testheft gibt, soll dieses nach dem einloggen automatisch gestartet werden.

**Comment by paflov** [comment]
Aktuelles Ergebnis aus dem JF dazu: Sehr gutes Feature, soll kommen!
