### ISSUE TITLE
Tooltips überdecken Reiter

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#27]
Ist manchmal nervig an die Reiter zu kommen, wenn zuvor ein Tooltip ausgelöst wurde:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/c88fa9b7-132b-473a-b96d-c87ec09fea66)

**Comment by tobhu1981** [comment]
Ist manchmal nervig an die Reiter zu kommen, wenn zuvor ein Tooltip ausgelöst wurde:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/c88fa9b7-132b-473a-b96d-c87ec09fea66)

**Comment by tobhu1981** [comment]
Bitte noch in den Arbeitsbereich auch machen. In den Systemeinstellungen ist es jetzt ok.

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/efbfc659-bf9f-43ad-92fe-9b91430025b1)

**Comment by jojohoch** [comment]
Das sieht doch nach einem Tooltip des Testcenters aus.

**Comment by tobhu1981** [comment]
funzt jetzt
