### ISSUE TITLE
Performance-Test: Unit-Calls weglassen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#284]
Wie viel kosten im Vergleich zu den Ressource-Calls die Unit-Calls?
Die könnten mit einem kleinem Umbau beim ersten laden eines Tests weggelassen werden.

Siehe:
https://app.zenhub.com/workspaces/testcenter-62626b86ce834f001598ef86/issues/gh/iqb-berlin/testcenter/267

**Comment by rhenck** [comment]
Wie aktuell ist das?

**Comment by paflov** [comment]
In TC 15 implementiert
