### ISSUE TITLE
Anzeige Blöcke TLK fehlerhaft???

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#29]
Ich habe folgende TLK in folgender Gruppe geöffnet:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/279feb85-8202-4190-9b80-7698219f63e7)
In der Gruppe werden 2 Booklets verwendet. Eines mit 2 Blöcken und eines mit 3 Blöcken und Units dazwischen. Letzteres ist nachfolgend zu sehen. Hier sind die Units zwischen den Blöcken markiert, die Probleme machen.
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/cc24dbdd-dea2-4a1f-a65a-d138989026d9)
Die markierten Units werden in der TLK nicht angezeigt, auch wenn ich mich in einer dieser Units als angemeldete Testperson in dem Booklet bewege:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/af1541c5-ef6a-4f0f-9383-f8e23c2368c2)
Liegt es vielleicht daran, dass die Units einen Alias haben, weil diese schon einmal im Booklet verwendet werden???

**Comment by tobhu1981** [comment]
Ich habe folgende TLK in folgender Gruppe geöffnet:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/279feb85-8202-4190-9b80-7698219f63e7)
In der Gruppe werden 2 Booklets verwendet. Eines mit 2 Blöcken und eines mit 3 Blöcken und Units dazwischen:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/cc24dbdd-dea2-4a1f-a65a-d138989026d9)
Die markierten Units dazwischen werden aber in der TLK nicht angezeigt, auch wenn ich mich als angemeldete Testperson in dem Booklet bewege:
![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/af1541c5-ef6a-4f0f-9383-f8e23c2368c2)
Liegt es vielleicht daran, dass die Units einen Alias haben, weil diese schon einmal im Booklet verwendet werden???

**Comment by tobhu1981** [comment]
Scheint am Alias zu liegen, ohne gehts. Soll das vielleicht so sein?

**Comment by paflov** [comment]
Nein, ist ein bug.

**Comment by paflov** [comment]
Fehler konnte nicht rekonstruiert werden. Beobachten.
