### ISSUE TITLE
Multi-Select und Benutzerrechte funktionieren nicht wie erwartet

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#300]
Bin nicht sicher, ob das als Bug zu werten ist, es ist zumindest verwirrend.

Steps:
- 2 Arbeitsbereiche anlegen in denen ein Benutzer nicht Mitglied ist
- Beide Bereiche in der ersten Spalte 'anhaken'
- auf der rechten Seite die Berechtigung den Benutzers wählen

Erwartet:
- Berechtigungen sind für alle gewählten Bereiche gesetzt

Tatsächlich:
- Nur für den zuletzt ausgewählten und blau hinterlegten Bereich sind die Rechte gesetzt.

Das Grundproblem scheint mir zu sein, dass es links mehrere Auswahlverfahren zugleich gibt - Haken und Zeilenauswahl. Das kann nur für Verwirrung sorgen. Mein Vorschlag wäre eines davon zu streichen. Und da man die Mehrfachauswahl via Checkbox wahrscheinlich nicht verlieren will, bleibt nur, die Zeilenauswahl zu entfernen bzw so zu gestalten, dass die immer mit der Checkbox synchron ist.

![image](https://github.com/iqb-berlin/testcenter/assets/446878/1d43f279-a2be-44eb-8b39-5bdabd9b91c3)

**Comment by tobhu1981** [comment]
Ich fänd das gut, wenn die Zeilenauswahl wegfällt, das ist nämlich wirklich verwirrend und ich habe schon ab und an auch Anfragen dazu bekommen.
