### ISSUE TITLE
Starter-Komponennten zusammenfassen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#303]
Vorbereitend darauf, dass weitere Rollen und Bereiche zu erwarten sind, sollten die Starter-Komponenten mal zusammengefasst und generischer gestaltet werden.

- app-root/admin-starter
- app-root/monitor-starter
- app-root/test-starter
 
Die basieren alle auf dem gleichen Datenmodell `AuthData` und `AccessObject` (app.interfaces.ts Z. 11, 22)

Es sollte nur eine starter-komponente geben, die die verschiedenen Bereiche anbietet, die man freigeben hat. 
Am ehesten am app-root/monitor-starter orientieren.

Die Gliederung muss sein

### AccessObject2

Usw.

Eventuell kann man auch den app-root/sys-check-starter da mit reinbringen, aber da bin ich mir nicht so sicher ob es eine gute Idee ist.

**Comment by huaning-yang** [comment]
Closed with #324
