### ISSUE TITLE
Verhalten von "Test beenden" bei nur einem Testheft

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter#316]
Momentan schickt einen der "Test beenden"-Button ja auf die Übersichtsseite. Wenn jetzt diese Übersichtsseite abgeschafft wird, wenn nur ein Testheft für den jeweiligen Schüler angelegt ist, dann müssen wir überlegen, was der Button in diesem Fall tun soll. Auf die Startseite des Tests zu leiten wäre verwirrend.

**Comment by paflov** [comment]
Die Übersichtsseite wird nicht abgeschafft -  es gibt ja immer noch den Fall, dass es mehrere Testhefte gibt. Ich denke, im Fall von test beenden landet man wie gehabt auf dieser Übersichtsseite, oder? Der einzige Unterschied ist nur, dass man sie beim einloggen überspringt, wenn nur ein Test da ist.

**Comment by jkoelm** [comment]
ok!
