### ISSUE TITLE
TLK: CustomText erweitern?

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#32]
Anfrage aus BW:
a.) Kann man die Reihenfolge „Überwachung starten“ und „Test ansehen“ vertauschen?
b.) Kann man die Schriftgröße ändern? Wunsch: Name des Tests soll kleiner sein und „Test anse-hen“ soll größer geschrieben sein?

**Comment by tobhu1981** [comment]
Anfrage aus BW:
a.) Kann man die Reihenfolge „Überwachung starten“ und „Test ansehen“ vertauschen?
b.) Kann man die Schriftgröße ändern? Wunsch: Name des Tests soll kleiner sein und „Test anse-hen“ soll größer geschrieben sein?

**Comment by paflov** [comment]
Solche Layoutfragen sind immer schwierig, denn über das Layout entscheiden nicht wir, sondern Jenny & Pauline. Wenn einem dieser Wunsch wichtig genug ist, müsste man ihn im Feature-Forum diskutieren.

**Comment by paflov** [comment]
Designfragen werden zZ nicht disktiert... "Wir machen eh ein Redesign"
