### ISSUE TITLE
Neuer Bereich "Profil" für Admins

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#320]
(Workspace-)Admins sollen in Zukunft ihre Email-Adresse und ihr Passwort selber ändern können (#215).

Der erste Schritt wäre einen neuen Bereich zu schaffen, der über den Admin-Starter zu erreichen ist "Profil".
Die erste Option hier wäre ein Knopf zum Ändern des Passwortes, analog zu dem im Super-Admin.

**Comment by huaning-yang** [comment]
Wie im Meeting besprochen wird das Feature erst mal verschoben, da es voraussichtlich nicht mehr benötigt wird.

**Comment by huaning-yang** [comment]
Wie im Meeting besprochen wird das Feature erst mal verschoben, da es voraussichtlich nicht mehr benötigt wird.
