### ISSUE TITLE
Neue Felder für unit xsd

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/testcenter#329]
Die https://raw.githubusercontent.com/iqb-berlin/testcenter-backend/master/definitions/vo_Unit.xsd
benötigt  zwei weitere Felder: Transcript und Reference
Das Studio verwendet diese Felder bereits. Sie müssen aus Sicht des Studios aber auch exportierbar sein.

aktuell:
```xml
...
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" />
      <xs:element name="Label" type="xs:string" />
      <xs:element name="Description" type="xs:string" minOccurs="0" />
      <xs:element name="Lastchange" type="xs:dateTime" minOccurs="0" />
    </xs:sequence>
...
```
zukünftig:

```xml
...
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" />
      <xs:element name="Label" type="xs:string" />
      <xs:element name="Description" type="xs:string" minOccurs="0" />
      <xs:element name="Transcript" type="xs:string" minOccurs="0" />
      <xs:element name="Reference" type="xs:string" minOccurs="0" />
      <xs:element name="Lastchange" type="xs:dateTime" minOccurs="0" />
    </xs:sequence>
...
```

**Comment by huaning-yang** [comment]
Ich habe die Änderungen mal vorgenommen und sollten dann ab Version 15.0.0 verfügbar sein.

@jojohoch: Was mir aber aufgefallen ist, ist dass die Reference (https://raw.githubusercontent.com/iqb-berlin/testcenter-backend/master/definitions/vo_Unit.xsd) zu der vo-Unit.xsd des alten Testcenter-Backends Repository verlinkt. Da das testcenter-backend Repository nicht mehr maintained wird, würde ich das Studio so anpassen, dass die vo_Unit.xsd (und alle anderen xsd's) aus dem testcenter repo verwendet werden.
