### ISSUE TITLE
TLK: Springe zu Block: Nachzügler

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#34]
Anfrage aus BW: Sollen Schüler Testbestandteile erst einen oder mehrere Tage später machen und war die Klasse zuletzt mittels TLK zu einem bestimmten Block geleitet wurden, fängt die Testung für die Nachzügler genau bei diesem Block an. Das kann laut BW ungünstig sein. Gebe es vielleicht die Möglichkeit via Zeitstempel (Bsp. es ist mehr als ein Tag seit der Testung vergangen) solche Nachzügler dann automatisch von vorne beginnen zu lassen?

**Comment by paflov** [comment]
Ja, ich habe mich schon gefragt, wann dieses Verhalten diskutiert werden will. Ich denke, das automatisiert zu entscheiden machen ist unklug. Vielleicht sollte man lieber ein Funktion einführen, noch-nicht-gestartete tests bei bedarf manuell zurück zu setzen, oder so... Discussion Needed.

**Comment by paflov** [comment]
Dublikat: 287
