### ISSUE TITLE
Traefik meckert über fehlende security header

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#344]
Betrifft docker-compose.prod.tls.yml und TC 14.10

**Comment by paflov** [comment]
testcenter-traefik               | time="2023-09-13T14:44:16Z" level=error msg="middleware \"tls-security-headers@docker\" does not exist" entryPointName=web routerName=testcenter-broadcasting-service@docker
testcenter-traefik               | time="2023-09-13T14:44:16Z" level=error msg="middleware \"tls-security-headers@docker\" does not exist" routerName=testcenter-frontend@docker entryPointName=web
testcenter-traefik               | time="2023-09-13T14:44:16Z" level=error msg="middleware \"tls-security-headers@docker\" does not exist" entryPointName=websecure routerName=websecure-testcenter-frontend@docker
testcenter-traefik               | time="2023-09-13T14:44:16Z" level=error msg="middleware \"tls-security-headers@docker\" does not exist" entryPointName=websecure routerName=websecure-testcenter-broadcasting-s

**Comment by rhenck** [comment]
Hier habe ich gestern noch ein Problem gesehen. Das Frontend sucht teilweise noch eine Headerdefinition, die es nicht gibt.

**Comment by paflov** [comment]
Ah, ok
