### ISSUE TITLE
Studienmonitor

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#35]
Wunsch aus BW: Unter Dateien gibt es eine Auflistung wie viele Dateien sich im Arbeitsbereich befinden, soweit ich Erinnerung habe sogar sortiert nach Dateientypen (Ressourcen, Units usw.). Gebe es die Möglichkeit eine solche Übersicht bzgl. der Anzahl auch unter: Ergebnisse/Antworten anzuzeigen?

**Comment by tobhu1981** [comment]
Anzahl der vorhandenen Antwortdateien.

**Comment by paflov** [comment]
In der Ansicht Ergebnisse/Antworten ist jede Zeile eine Gruppe (für die Daten irgendeiner Art, also Antworte, Logs oder Reviews vorliegen). Es soll also die Anzahl der Gruppen angezeigt werden?

**Comment by tobhu1981** [comment]
Ja ich glaube so war der Wunsch aus BW. Ich glaube die wollten das um schnell zu sehen, welche Tests schon gestartet wurden. Ich glaube die hatten Fälle mit sehr vielen Groups in ihren Testtaker-Xmls.

**Comment by huaning-yang** [comment]
@tobhu1981 Sorry, ich bin leider immer noch etwas verwirrt was gewollt ist. Sollen die anzahl von Gruppenteilnehmern angezeigt werden oder die Anzahl der gegebenen Antworten der Gruppenteilnehmer? Also wenn es zwei User in einer gruppe gibt, die beide Antworten(nehmen wir an: ein User hat 3 und der andere user 4 ) gegeben haben. Soll dann die Summe der Antworten (im diesem Fall 7) oder 2 angezeigt werden, weil 2 Nutzer  aus der Gruppe Antworten abgegeben haben?

**Comment by tobhu1981** [comment]
Ich habe jetzt noch einmal in den alten Trellokarten nachgesehen und folgendes dazu von Frau Stefanica gefunden:

 "Ich hatte diese Ergebnisübersicht in Testcenter als eine Art Studienmonitor gesehen. (Das ist sie ja auch, aber aktuell für mich noch nicht so hilfreich, wie ich es mir erhofft hatte.)
Für mich wäre es hilfreich / gut zu wissen:
-wie viele SuS aus jeder Klasse / Gruppe haben das Testheft gestartet (oder wie viele haben es nicht gestartet)
-von denen, die es gestartet haben: wie viele Seiten wurden mindestens angeschaut (das ist so ähnlich wie das Aufgaben min); wie viele Seiten wurden maximal angeschaut (Aufgaben max)

Wir können gerne mal in Ruhe darüber sprechen, was hilfreich (für uns) in so einem Studienmonitor wäre."

Wäre wohl doch etwas umfangreicher, aber die Informationen könnten hilfreich sein und das Testcenter noch komfortabler und übersichtlicher machen. Was meinst du? Mal mit Martin drüber sprechen, ob es dafür ein Zeitfenster gibt?

**Comment by paflov** [comment]
Na Ja, der Studienmonitor ist als neues schon lange geplant und wird immer wieder verschoben. Das ist tatsächlich ein separates Thema, und nichts, was man so mal eben implementiert. Dann wandle ich dieses Ticket erstmal um in ein Konzept-Ticket...

**Comment by paflov** [comment]
Ansage vom Team-Meeting 21.9. : Wiederherstellung der Funktionalität des alten Gruppen-Monitors.

**Comment by paflov** [comment]
Ansage MM Team-Meeting 30.11: Der neue Studienmonitor ist der frühere MO modus auf Workspaces.
