### ISSUE TITLE
SysCheck: An Login binden

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#352]

**Comment by paflov** [comment]
- 1. Ein weiterer run-modi ist erforderlich: syscheck.
- Ist mindestens ein User auf diesem Workspace mit diesem Modus definiert, so kann der SysCheck nur nach Login  gestartet werden.
- Auf der Login-Seite werden auch SysChecks wie Booklets gelistet.
- Ist kein User mit diesem neuen Modus in einem Workspace definiert, kann der SystemCheck wie gehabt über den Button SysChecks erreicht werden.

**Comment by tobhu1981** [comment]
## Ergebnis Erprobung Login "sys-check-login" auf TC1 in V15.2.0
* sobald der ursprüngliche Gruppenname "sample_group" in der Testtaker, in der sich der neue Login `<Login mode="sys-check-login" name="sys-check" />` befindet, geändert wird, kommt eine 500er Meldung nach der Anmeldung mit "sys-check". Es ist also nicht möglich den Login in einer anderen Gruppe zu verwenden.

**Comment by nam-du-iqb** [comment]
1) Das scheint auch ein Problem mit allen logins zu sein. Müssen wir uns überlegen ob das so gewollt ist oder nicht. Ich mache dafür ein neues Ticket auf.
2) Das war ein Bug und ist bereits gefixt. Ich habe dort auch einen e2e Test geschrieben, der diesen Ablauf testet.
