### ISSUE TITLE
update.sh schreibt env-varibale VERSION nicht richtig

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#354]
Da erscheint immer ein Slash vorn der Versionsnummer in .env.

**Comment by rhenck** [comment]
Das hast du offenbar bereits gelöst: https://github.com/iqb-berlin/testcenter/commit/492817f1266c61eb0cb82315e987bec8fb36a425

Ich kanns atm auch nicht mehr reproduzieren.
