### ISSUE TITLE
Systemcheck: Browserverlauf muss geleert werden, damit der Button erscheint

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#356]
Ich habe soeben den beispielhaften Systemcheck von hier getestet: https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/2.7-System-Check

Ich weiß nicht, ob das Problem, auf das ich stieß, zufällig zustande kam oder ob es systematisch auftritt.

# Anzeigeproblem
* Es wurde nicht direkt ein Button im Testcenter angezeigt (Browser: Microsoft Edge), sondern erst nachdem ich meinen eigenen Browserverlauf gelöscht hatte und die Seite neu geladen habe (kam durch Zufall auf die Idee) . Danach funktionierte es. Bei Firefox scheint das Problem nicht aufgetreten zu sein.
* Ich weiß nicht, ob das ein mögliches Szenario ist, das den Systemcheck für die durchführenden Personen erschwert, wenn sie vielleicht zu einem früheren Zeitpunkt schon einmal mit dem Zielendgerät auf die Seite gegangen sind? Vielleicht gibt es da einen Workaround?

**Comment by huaning-yang** [comment]
Ich kann das leider nicht reproduzieren. 
Weißt du noch mit welcher Testcenter Version du das gemacht hast? 

Und nur um sicher zu gehen, um welchen Button genau handelt es sich?
Wenn man von der Startseite (wo sich die Login Maske befindet) auf System-Check klickt?
![Screenshot from 2023-10-18 14-54-31](https://github.com/iqb-berlin/testcenter/assets/78593320/6c07a00a-9c71-4026-9fec-df52a755895d)
Also erscheint der Button in diesem Screenshot nicht oder handelt es sich um einen anderen Button?

**Comment by franikowsp** [comment]
Ich habe es mit der Version von vor etwa 3 Wochen gemacht.

Es handelte sich um den Button "System-Check" (den linken) selbst:

![image](https://github.com/iqb-berlin/testcenter/assets/60889089/d36f27bf-c7f9-4cf6-8aba-830f0e9f4418)

Möglicherweise tritt das Problem jetzt auch nicht mehr auf, da der Button jetzt immer beim (ersten) Aufrufen da ist 🤔

**Comment by huaning-yang** [comment]
Ich würde das hier dann erstmal unter Vorbehalt schließen.
Sollte es wieder auftreten werde ich mich darum kümmern.
