### ISSUE TITLE
Veraltete Node-Version für Frontend und BS

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#374]

**Comment by paflov** [comment]
Und eventuell deprecated NPM pakete.

**Comment by paflov** [comment]
Folgende Version wäre gut:
NODE_VERSION=20.9.0-bookworm-slim

**Comment by paflov** [comment]
Noch ein hinweis: Beim Frontend ist es nicht SO wichtig wie beim BS, da das node image nur dev betrifft.

**Comment by huaning-yang** [comment]
Closed with #394
