### ISSUE TITLE
TLS_enabled wird nicht als Standart genommen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#377]
Ich meine auch zwischendurch das gleiche zum File-Service gelesen zu haben. Kanns gerade nur für BS repoduzieren.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--680a14440fe9d8e49549cb1b537bdded34c1e527/Screenshot%20from%202023-10-20%2015-43-07.png)

**Comment by paflov** [comment]
Problem ist nicht die CSP sondern, dass er weiterhin standartmäßig versucht die Dienste über http anzusprechen statt https, wenn TLS_ENABLEd nicht gesetzt wird (was in Prod nicht sein sollte, denn da ist TLS nun Pflicht).
