### ISSUE TITLE
SuperAdmin: Icons auf Buttons schief

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#379]
Ist nicht mehr die ungekapselte Component.

Keine Ahnung, warum das so ist. Ich sehe 2,5 Ansätze:
- Auf Icons in Verbindung mit mat-raised-button verzichten und andere Buttons nehmen. Die Doku hat auch kein Beispiel, waruas ich schließe, dass es so nicht gedacht ist.
- Reparieren mit "margin: auto" auf dem Icon
- Rausfinden, ob es einen anderen Grund gibt, warum die schief sind. Habe ein paar Minuten gesucht, aber nix gefunden.

**Comment by huaning-yang** [comment]
Ich habe jetzt auch keinen Grund gefunden weshalb man sie nicht mehr zusammen funktionieren, aber andere haben das Problem zumindest auch.
Die Doku sieht für buttons die nur ein icon enthalten mat-icon-button, mat-fab oder mat-mini-fabs vor.
Gibts ne Präferenz welche Art von Button wir benutzen wollen? @paflov @rhenck 

Der raised-button aber mit margin:auto auf dem Icon:
![mat-raised-button-fixed](https://github.com/iqb-berlin/testcenter/assets/78593320/c733031b-17d5-4959-beaa-3461bbd2efac)

mat-fab button:
![mat-fab](https://github.com/iqb-berlin/testcenter/assets/78593320/99d2adbe-f45b-4ce3-a46a-1777e586b46f)

mat-mini-fab button:
![mat-mini-fab](https://github.com/iqb-berlin/testcenter/assets/78593320/9bf2c5e0-e11b-4bb4-9569-aa2f43e814e4)

**Comment by rhenck** [comment]
Ich finde die eckigen eigentlich am schönsten. Ist aber vielleicht auch nur der Gewohnheit wegen. Kann mich auch mit den Fabs anfreunden.
Also meine Präferenz wäre Variante 2, aber entscheide du ruhig, Huaning.

**Comment by rhenck** [comment]
Schau bei der Gelegenheit bitte mal, dass wir nicht 2x das gleiche Icon für verschiedene Dinge verwenden.

**Comment by rhenck** [comment]
Auch nice wäre es, wenn die Buttons deaktiviert wären, solange man nix ausgewählt hat.
