### ISSUE TITLE
Fehlermeldung bei Starten eines Booklets

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#38]
### Testung SuperAdmin: run-demo:
Immer wenn ich ein Booklet starte erscheint diese Meldung:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/4b91be15-949e-4335-b066-17e8a5814e5f)

Die kann ich dann einfach schließen und normal weiterarbeiten. Die verwendeten Testdateien befinden sich im AB: Testung_SuperAdmin.

**Comment by tobhu1981** [comment]
### Testung SuperAdmin: run-demo:
Immer wenn ich ein Booklet starte erscheint diese Meldung:

![grafik.png](https://images.zenhubusercontent.com/60950a18ca5c9c68519629ae/4b91be15-949e-4335-b066-17e8a5814e5f)

Die kann ich dann einfach schließen und normal weiterarbeiten. Die verwendeten Testdateien befinden sich im AB: Testung_SuperAdmin.

**Comment by jojohoch** [comment]
Kann es sein, dass es sich hier um Aufgaben mit GeoGebra-Elementen handelt und dass Geogebra auf dem Testcenter nicht verfügbar ist?

**Comment by tobhu1981** [comment]
Ich glaub hier geht grad was durcheinander. @Philipp: Hast du die letzten Tickets aus Versehen Joachim zugewiesen? Die waren bestimmt für mich oder?

**Comment by paflov** [comment]
Ja genau, hab die falsch zugewiesen tut mir leid!

**Comment by tobhu1981** [comment]
Nicht mehr gesehen
