### ISSUE TITLE
Navigationsleiste: erste Unit eines gesperrten Blocks nicht ausgegraut

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/testcenter#382]
Units in gesperrten Blöcke werden vor ihrer Aktivierung durch Testleitungskonsole/Freigabewort in der Navigationsleiste grau dargestellt. Das ist bei der jeweils erste Unit innerhalb dieser Sperre nicht der Fall (siehe Screenshot Unit 6, 11, 15) - sollte es aber.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87d00b62e185ebf93224b359bb42ad8d61d8d32d/Screenshot%202023-10-20%20152022.png)

**Comment by paflov** [comment]
Man kann ja drauf klicken und dorthin gehen, daher ist er mit Absicht nicht ausgegraut. Anders würde man ja gar nicht in diesen Block kommen und keine Chance haben das Freigabewort einzugeben.
