### ISSUE TITLE
Security Header verbessern

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#387]
- "traefik.http.middlewares.security-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.security-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=no-referrer"

**Comment by paflov** [comment]
?

**Comment by rhenck** [comment]
> ?

Sven hat noch weitere Einstellungen gefunden, die von KeyCloak gemacht werden und bei denen es uns sinnvoll erschien, die generell zu übernehmen.

**Comment by paflov** [comment]
Na, dann.
