### ISSUE TITLE
Mögliche Entspannung der name-Restriktion beim Login

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#388]
Ich bräuchte leider noch einen Nachtrag, der vermutlich in eine ähnliche Richtung wie #332 geht: Für unseren Systemcheck gibt es noch ein separates Testheft. Um nicht zu viele verschiedene, eigene Codes für die Schulen im Umlauf zu geben (es wird auf jeden Fall einen für den System-Check geben und die Zugangsdaten sollten möglichst analog sein), soll die übliche Schul-ID mit einem zusätzlichen zweistelligen Buchstaben-Code vergeben werden. Das Muster ist dieses: `123456AB`

# Beschreibung
* Wäre es möglich, die ID-Restriktion auch für Login-Namen zu entspannen, sodass das `name`-Attribut auch für mit Zahlen beginnende Einträge valide wird?
```xml
    <Login mode="run-hot-return" name="123456AB" pw="XXXX">
      <Booklet>booklet1</Booklet>
    </Login>
```
* Die Änderung müsste dann leider bis 24.11. erfolgen, da dann der System-Check ausgerollt wird. Andernfalls müssten wir eine Übergangslösung vorbereiten, die aber möglicherweise zusätzliche Umstände bereiten.

**Comment by paflov** [comment]
Bis zum  24.11. ist das leider nicht zu schaffen.

**Comment by franikowsp** [comment]
Danke für die Rückmeldung - dann können wir erstmal eine Übergangslösung fahren.

**Comment by franikowsp** [comment]
@paflov: Doch noch einmal eine frische Rückfrage dazu, da es für die BiSta-Test-Pilotierung noch relevant wäre. 

**Hintergrund:** Ich würde die Logins gern auf Kleinbuchstaben und Ziffern beschränken.

Das große Problem bei Kleinbuchstaben ist, dass iPads (die sehr verbreitet sind) den ersten Buchstaben immer groß setzen (und die erste Stelle müsste derzeit ja immer ein Buchstabe sein). Demnach müsste manuell die Großschreibung bei diesen Geräten ausgestellt werden (bei Klassentestungen ist das natürlich aufwendig zu instruieren). Eine Großschreibung zu Beginn ist keine gute Alternative, da es umgekehrt andere Geräte (insbesondere dann Laptops bzw. Geräte mit externer Tastatur) benachteiligen würde und dasselbe Problem zufolge hätte.

Wäre es daher doch noch möglich, diese Restriktion zu entfernen?

**Comment by paflov** [comment]
Könnte ich schon machen, dann für die nächste Minor Version 15.1.0, die in den nächsten Wochen fällig ist. Falls ihr das noch in der 14 braucht, sehe ich keine Chance.

**Comment by franikowsp** [comment]
Für v15 (BiStaTest-Pilot) wäre das völlig ausreichend! Wann wäre da ca. das Datum? Es müsste sicher vor der Auslieferung der Offline-Version erfolgen?

**Comment by paflov** [comment]
Ich werde die 15.1.0 bis spätestens Ende nächster Woche veröffentlichen und bringe das dann noch unter. Wann welcher Server dann tatsächlich geupdatet wird weiß ich nicht, und muss leider ausgehandelt werden weil viele Projekte immer Updates blockieren.

**Comment by paflov** [comment]
Ist bereits umgesetzt und wird in der 15.1.0 enthalten sein!
