### ISSUE TITLE
Der Link "Developer's Guide" in README.md funktioniert nicht

### ISSUE THREAD

**Issue by dan-barbulescu-dev** [iqb-berlin/testcenter#390]
Der Link "[Developer's Guide](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/developer-guide.html)" in README.md funktioniert nicht.

![404](https://github.com/iqb-berlin/testcenter/assets/25221073/aad208a9-af4f-43a8-8fd2-80f843df539a)

**Comment by rhenck** [comment]
Hier der Commit, der den kaputt gemacht hat:
https://github.com/iqb-berlin/testcenter/commit/ff7c86a9a945c013605b42c26b77eeaa72a61339
