### ISSUE TITLE
System-Check: Dialog "Bericht senden"

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#393]
Leider bräuchte ich ebenfalls bis Dienstagabend eine Rückmeldung, ob das Folgende noch realisierbar ist:

In Vorbereitung des System-Checks hat sich noch ein Änderungswunsch für das Absenden des Berichts nach dem System-Check ergeben. Das betrifft vermutlich diese Zeilen:

https://github.com/iqb-berlin/testcenter/blob/e4ff7d098f21714086210cfdda2c17a2c7c47de0/frontend/src/app/sys-check/report/save-report/save-report.component.html#L4C1-L24C24

Hintergrund ist, dass wir die Login-Informationen gern konsistent halten wollen, damit es nicht zu Verwirrungen oder Vertauschungen kommt. So wären die Eingabefelder dieselben und hätten auch dieselbe Reihenfolge wie im Testcenter. Ein Vorschlag wäre: (falls es möglich ist, den ersten Teil noch als customtext (vielleicht `syscheck_report_text` oder so?) einzuführen, wäre das natürlich auch noch super. Falls das Passwort-Feld auch auf Bedarf noch sichtbar gemacht werden könnte (mit dem Augen-Symbol) wie auch beim Zugang im Testcenter, wäre das zudem noch sehr praktisch.

```{xml}
  <mat-dialog-content>
    <p>
      Vielen Dank. Damit wir die Angaben Ihrer Schule zuordnen können, geben Sie bitte den Anmeldenamen und das Kennwort ein, die Ihnen mitgeteilt wurden.
    </p>
    <mat-form-field appearance="outline">
      <input
        matInput
        formControlName="title"
        [placeholder]="'Anmeldename'| customtext:'syscheck_report_id' | async"
      >
    </mat-form-field>
    <mat-form-field appearance="outline">
      <input matInput type="password" formControlName="key" placeholder="Kennwort">
    </mat-form-field>
  </mat-dialog-content>
```

Meines Wissens ist unser System-Check (und auch der andere verfügbare, den wir ebenfalls von BiStaTest aus betreuen) der einzige, der aktuell läuft, sodass eine systemweite Änderung vermutlich unproblematisch wäre.

Mir ist darüber hinaus aufgefallen, dass die CustomTexts im System-Check scheinbar ohne Effekt waren (obwohl an vermeintlich richtiger Stelle eingefügt und auch die vermeintlich richtigen IDs verwendet).

**Comment by franikowsp** [comment]
Für den [aktuellen System-Check](https://www.iqb-testcenter.de/#/check/139/BISTA_PILOT2024/w) waren das folgende CustomTexts:

```{xml}
	<Config savekey="iqb-pilot2024">
		
		<!-- D: Festlegung Grenzwerte für die Internet Bandbreite  -->
		<UploadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="10000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">100000, 200000, 400000, 800000</UploadSpeed>
		<DownloadSpeed min="1024" good="2048" maxDevianceBytesPerSecond="200000" maxErrorsPerSequence="0" maxSequenceRepetitions="15">400000, 800000, 1600000, 3200000</DownloadSpeed>
		
		<CustomText key="syscheck_intro">Dieser Systemcheck soll gewährleisten, dass der von Ihnen verwendete Computer (Desktop / Laptop / Tablet) für die Testung und Befragung geeignet ist.</CustomText>
		<CustomText key="syscheck_questionsintro"></CustomText>
		<CustomText key="syscheck_report_id">Anmeldename</CustomText>
		
		<!-- E: Fragebogen anlegen  -->
		<Q id="1" type="header" prompt="Die folgenden Fragen helfen uns, die Ergebnisse des System-Checks einordnen zu können."></Q>
		...
	</Config>
```

**Comment by paflov** [comment]
Dass die CustomTexts gar nicht erscheinen ist ein Bug. Der hat ein extra Ticket bekommen (#395).
Ich versuche vor dem Update, das wir am Mittwoch fahren müssen, den noch zu fixen. Wenn noch Zeit bleibt baue ich auch die zusätzlichen CustomTexts noch mit ein.
