### ISSUE TITLE
Unitmenu Schriftausrichtung anpassen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#399]
JH:
1. In der Navigationsleiste dieser Testcenterinstanz sind die Überschriften nicht zentriert, daher hängen umgebrochene Nummer oder Buchstaben sehr weit links - das bräuchten wir bitte wieder zentriert.

jetzt: 
<img width="98" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1lyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8e04c9d68a242db73c2b65787bc72ebb5c83a41/vorher.png" alt="vorher.png" />
vorher: 
<img width="182" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a83ca09266eb3366601199eecc0108dfffebe322/nachher.png" alt="nachher.png" />

Falls dies nicht den Maßgabe von JK/PK widerspricht?

**Comment by helfjama** [comment]
Geht es jetzt @rhenck ?

**Comment by rhenck** [comment]
> Geht es jetzt @rhenck ?

Nope. Unverändert

**Comment by rhenck** [comment]
Ah sorry, wenn ich über die Zenhub-Website gehe, kann ich sie sehen.

**Comment by rhenck** [comment]
Aber auch hier nochmal der Hinweis: Wenn ich mich damit befassen soll, wird es sehr eng, dass das dieses Jahr noch passiert.

**Comment by paflov** [comment]
Habs mal eben erledigt, weg ist weg
