### ISSUE TITLE
Passwortsperre: Hinweise automatische Großschreibung

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/testcenter#403]
Wie besprochen bräuchte es auf der Passwortsperrenseite noch einen Hinweis, dass immer großgeschrieben wird.
Philipp @franikowsp spricht noch mit Silke und macht dann einen Vorschlag.

**Comment by paflov** [comment]
<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ltQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b181a5a331761263b0cb06f445ea34a2f0d592b/Screenshot%202024-01-08%20at%2013-54-55%20IQB-Testcenter%20U1.png" alt="Screenshot 2024-01-08 at 13-54-55 IQB-Testcenter U1.png" />
Habt ihr euch das in etwa so vorgestellt, oder wie?

**Comment by helfjama** [comment]
@paflov Irgendwie lädt das Bild bei mir nicht? ("Non-Image content-type returned")

**Comment by paflov** [comment]
Das ist immer, wenn ich die Bilder über ZenHUb hochlade.. muss ich mir mal abgewöhnen.

**Comment by paflov** [comment]
Jetzt müsste es sichtbar sein

**Comment by helfjama** [comment]
Ich nehme es mit zu uns ins Team und melde mich dann zurück!

**Comment by paflov** [comment]
Wann denn? Wäre gut zu wissen zwecks Releaseplanung...

**Comment by helfjama** [comment]
Spätestens am Mittwoch, wir sind noch nicht glücklich wie es gerade ist und arbeiten noch an einem Vorschlag.

**Comment by helfjama** [comment]
Der Release kommt ja sowieso erst frühestens Februar? Martin hatte uns zugesagt auf unsere HT-Abgabe zu warten?
