### ISSUE TITLE
IQB Tastatur für Passworteingabe und Blocksperre

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/testcenter#405]
Wir würden vorschlagen die IQB-Tastatur auch dafür statt der Systemtastatur einzublenden (gab z.B.  Probleme mit nicht auswählbaren Wortvorschlägen). Du würdest das dann mit Martin besprechen @paflov ?

**Comment by paflov** [comment]
Habe es heute im Meeting vorgebracht und Martin lehnt es rundheraus ab. Weitere Diskussionen dann mit ihm...
