### ISSUE TITLE
Sleep-Mode

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#406]
# Gerät sollte während der Testung nicht in den Sleep-Mode fallen

Aufgefallen ist mir das bei Audios (bei Videos tritt das Problem vermutlich eher nicht auf, aber das habe ich nicht getestet). Wenn die Geräte einen Sleep-Timer eingestellt haben, der < 5 Minuten ist (mache ich bei meinen Privatgeräten, die nicht PC sind, zumindest), fallen sie bei zu langen "Pausen" in den Sleep-Mode. Ggf. unterbricht das die Testsitzung, wenn man nicht weiß, wie man wieder in die Sitzung zurückgelangt und man könnte sich dann potentiell auch "verirren" und ggf. die aktuelle Sitzung versehentlich abbrechen (durch Schließen des Browsers, etc.).

**Aufgefallen auf:** Android-Tablet (Samsung Galaxy), Chrome Browser

**Comment by paflov** [comment]
Ich frage mich nur, was man dagegen tun soll? Müssen wir mal brainstormen.

**Comment by paflov** [comment]
@huaning-yang Könntest du recherchieren, ob man verhindern kann, dass das Gerät während der laufenden Testung in Standby oder was auch immer geht?
Hängt auch mit Ticket [#148](https://github.com/iqb-berlin/testcenter/issues/148) zusammen.

**Comment by nam-du-iqb** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API sieht vielversprechend aus

**Comment by huaning-yang** [comment]
Die Screen wakelock api habe ich schon auf nem branch getestet. Auf Desktop browsern funktioniert das gut (auch bei Mozilla, obwohl es da offiziell noch nicht unterstützt wird)
Allerdings hat es auf Tablets nicht wie gewünscht funktioniert, da wollte ich noch mehr testen

**Comment by nam-du-iqb** [comment]
Wird statt der Wakelock API nun mit dem "Kiosk Modus" gelöst. 
Auf iOS heißt das ["geführter Zugriff/Guided Access" ](https://support.apple.com/de-de/111795).
Auf Android heißt das ["Bildschirm fixieren/Pin App"](https://support.google.com/android/answer/9455138?hl=de)

Eine Anleitung auf iOS gibt es im [Wiki](https://scm.cms.hu-berlin.de/groups/iqb/-/wikis/iPad:-Testcenter-als-PWA-(Vollbildmodus)-und-Gef%C3%BChrter-Zugriff-(Kiosk-Mode)#kioskmode).
