### ISSUE TITLE
V15: hot-restart: presentation und response complete haben keine Funktion

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#412]
Wenn beide OFF sind, muss man trotzdem Pflichtfelder ausfüllen und sich alles ansehen bzw. anhören.

**Comment by paflov** [comment]
Kann ich trotzdem nicht reproduzieren. OFF, ON, ALWAYS - funktioniert alles bei mir.

**Comment by tobhu1981** [comment]
DenyNavigationOnIncomplete war auf ON. Hat sich also erledigt.

**Comment by tobhu1981** [comment]
DenyNavigationOnIncomplete war auf ON, hat sich also erledigt
