### ISSUE TITLE
V15: TLK: Markierung einzelner TP nicht möglich

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#414]
Ich melde mich mit den Daten der TLK an. Anschließend melde ich als TP an. In der TLK wird die neue TP angezeigt, ich kann diese Person aber nicht markieren, nachdem die Funktion:  "Alle Tests gleichzeitig steuern" ausgeschaltet ist. Erst wenn ich die Seite der TLK neulade, kann ich die Person markieren.

<img width="1902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5FQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84f3ff03495d1ff70cdc66990ea0f6c592d09a41/Screenshot%20from%202023-12-08%2012-08-38.png" alt="Screenshot from 2023-12-08 12-08-38.png" />

**Comment by paflov** [comment]
Müssen wir auch drüber reden, kann ich nicht reproduzieren.

**Comment by tobhu1981** [comment]
Nicht mehr reproduzierbar
