### ISSUE TITLE
V15: TLK: Pausierung nicht möglich

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#415]
Eventuell hängt das alles mit Ticket #414 zusammen. Ich hatte es einmal geschafft eine TP zu markieren und einen Pause-Befehl abzusetzen. Dieser kam aber nicht an und der Test konnte weiter bearbeitet werden.

**Comment by paflov** [comment]
Müssen wir auch drüber reden, kann ich nicht reproduzieren.

**Comment by tobhu1981** [comment]
Nicht mehr reproduzierbar
