### ISSUE TITLE
V15: GGB: GeoGebra lädt nicht

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#416]

**Comment by franikowsp** [comment]
Im neuen Center habe ich GeoGebra ausgetest und irgendwie erhalte ich die folgenden Fehlermeldungen, ohne dass eine GGB-Datei lädt (es ist der Player 2.3.0-beta).

Failed to load resource: the server responded with a status of 400 ()
233.21390b586b0a01b8.js:1 Object
about:srcdoc:1  Refused to execute script from 'https://testcenter.iqb.hu-berlin.de/fs/file/x68p1k_h1gpuzj6edgg8jy4i/ws_4/Resource/GeoGebra/GeoGebra/deployggb.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.

**Comment by paflov** [comment]
Könntest du mir bitte Aufgabe + Player + GGB-Paket zukommen lassen, damit ich es nachbauen kann?
