### ISSUE TITLE
V15: response complete Meldung manchmal nicht vollständig

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#418]
Bei den Cypress-Testungen ist aufgefallen, dass manchmal, wenn versucht wird ohne responses complete weiterzublättern in dem Dialog nicht "bearbeitet" enthalten ist. Das passiert aber nicht immer.

**Comment by paflov** [comment]
@huaning-yang Vielleicht kannst du mit Tobias das mal genau nachvollziehen/nachstellen und entweder selbst fixen oder wenigstens die Umstände klären, unter denen das passiert.

**Comment by paflov** [comment]
ist lange nicht mehr aufgetreten und vermutlich im Rahmen des refactorings der e2e behoben.
