### ISSUE TITLE
Verona 5.2

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter#428]
Zu den drei pagingModes soll 'buttons' hinzukommen. Es ist eine Ableitung aus 'separate', die Seiten sind also getrennt voneinander zu blättern. Aber es sollen Buttons eingeblendet werden, die die Seiten-Navigation ermöglichen. Diese Buttons sollen also nicht Teil der Unit-Definition sein, sondern bei jeder Unit - sofern es weitere Seiten gibt - automatisch eingeblendet sein.

**Comment by paflov** [comment]
Erfordert zunächst Implementation im Simple-Player.
