### ISSUE TITLE
aktuellster Chrome wird nicht unterstützt

### ISSUE THREAD

**Issue by jurei733** [iqb-berlin/testcenter#429]
<img width="1207" alt="Bildschirmfoto 2024-01-29 um 14 54 29" src="https://github.com/iqb-berlin/testcenter/assets/67505990/3137b02a-3d27-41d8-987d-c9b544c3fcc7">

# Fehlerbeschreibung

Beim Aufrufen sollte Chrome mit aktuellster Browserversion erkannt werden.
Es wird jedoch gewarnt, dass der Browser nicht unterstützt wird und dies zu Fehler führen kann.

```
Objectloaded: 1992[[Prototype]]: Object
/#/r/login/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

# Kontext 

**URL**: https://testcenter.iqb.hu-berlin.de/#/r/login/

**Browser**:  Chrome ist auf dem neuesten Stand
Version 121.0.6167.85 (Offizieller Build) (arm64)

**Comment by paflov** [comment]
Browserslist hat Chrome 121 anscheinend  noch nicht aufgenommen!

https://browsersl.ist/#q=last+2+chrome

**Comment by D31nH31mbrau3r** [comment]
In unserem Testsystem sind die neusten Versionen immer noch als "nicht-aktuell" angezeigt. 

Der Befehl für die Browserslist über den Link gibt folgendes aus: "Unknown browser query last 2 chrome. Maybe you are using old Browserslist or made typo in query."

wenn man stattdessen "last 2 **versions**" oder "last 2 chrome **versions**" eingibt, bekommt man die aktuellsten versionen angezeigt!

**Comment by paflov** [comment]
Hm. ich glaube eher, ich habe den Link nicht vollständig kopiert und inzwischen sind die Versionen aufgenommen. Bin aber irritiert und werde das prüfen :)
