### ISSUE TITLE
Fehlermeldung beim Abbrechen des Unit Ladevorganges

### ISSUE THREAD

**Issue by jurei733** [iqb-berlin/testcenter#430]
# Fehlerbeschreibung

Meldet man sich im iqb-testcenter an und die Unit wird geladen und man geht in der Zwischenzeit über das Hamburger Menü auf den Menüpunkt Test beenden und wählt diesen aus, so wird der Fehler geworfen.

# Kontext
**Server**: OCBA / Local / etc.

**Frontend-Version**: 

**Backend-Version**: 

**Testdaten (player etc.)**:

**URL**: https://www.iqb-testcenter.de/#/r/test-starter

**Modus**:

**Browser**: 

# Screenshot
![image](https://github.com/iqb-berlin/testcenter/assets/67505990/3e9fec44-6d93-4805-a522-e047e83ac413)

**Comment by paflov** [comment]
behoben in tc 15
