### ISSUE TITLE
Veränderung der Output-Struktur des Testcenter-Reviews

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#432]
# Spalten

* Eintrag "category: " kann raus (kann sie nicht zuordnen, die anderen machen Sinn)
* Eintrag  "category: content", "category: design", "category: tech" R-lesbar machen, d. h. ": " gegen Unterstrich ersetzen und die Einträge auf WAHR (statt "X") bzw. FALSCH (statt LEER) setzen (oder zumindest WAHR und LEER)
* Eintrag "entry": aktuell wird der Name der reviewenden Personen immer vorangestellt, z. B. "Philipp: MEIN KOMMENTAR" - es wäre praktisch, würde das separiert werden, z. B. Spalte "name" / "reviewer" (z. B. "Philipp") und Spalte "entry" (z. B. "MEIN KOMMENTAR")
* Außerdem interessieren uns für technische Rückmeldungen auch dringend vor allem Browser- (und Version) und ggf. Gerätespezifikationen. Sofern diese noch geloggt werden könnten (z. B. als JSON-String, wie auch bei den Testcenterlogs oder als separate Spalten), wäre das extrem hilfreich.

**Beispiel:** [Entwurf_Log.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cf29206ff6d61fc80a85dfd5a268706b1650af7/Entwurf_Log.xlsx)

**Comment by paflov** [comment]
@mechtelm können wir das so machen?

**Comment by mechtelm** [comment]
Der Review-Bereich muss sowieso überarbeitet werden. Wichtig wäre z. B. , dass der Kommentar editierbar wird. Über Kategorien würde ich auch gern nochmal ein Meeting machen und also die Erfahrungen und Wünsche einsammeln.

Ansonsten könnte der JSON-Abruf beliebig geändert werden, da den niemand nutzt (Abruf über Admin-UI nur als CSV). Die Kategorie-Property dann z. B. als "category": ["design", "content"]

**Comment by paflov** [comment]
Ich teile das mal auf folgende Tickets auf und mache dieses hier zu:
* Reviews sollen editierbar sein #437 
* Reviews sollen UserAgent-Daten enthalten #438
* Verbesserungen an der Ausgabe der Reviews #439
