### ISSUE TITLE
Browserslist Aktualitätsproblem bei allen Browsern

### ISSUE THREAD

**Issue by D31nH31mbrau3r** [iqb-berlin/testcenter#434]
In unserem Testsystem sind die neusten Browser-Versionen immer noch als "nicht-aktuell" angezeigt. 

Der Befehl für die Browserslist über den Link gibt folgendes aus: "Unknown browser query last 2 chrome. Maybe you are using old Browserslist or made typo in query."

wenn man stattdessen "last 2 **versions**" oder "last 2 chrome **versions**" eingibt, bekommt man die aktuellsten versionen angezeigt (also wohl auch aufgenommen). Kann das Problem womöglich hier liegen?

Original:
Browserslist hat Chrome 121 anscheinend  noch nicht aufgenommen!

https://browsersl.ist/#q=last+2+chrome

_Originally posted by @paflov in https://github.com/iqb-berlin/testcenter/issues/429#issuecomment-1916853370_

**Comment by paflov** [comment]
Hm. ich glaube eher, ich habe den Link nicht vollständig kopiert und inzwischen sind die Versionen aufgenommen. Bin aber irritiert und werde das prüfen :)
