### ISSUE TITLE
Reviews sollen editierbar sein

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#437]
Zitat MM #431 
* Wichtig wäre z. B. , dass der Kommentar editierbar wird.

**Comment by rhenck** [comment]
Mir ist nicht klar, was hier genau passieren soll bzw. ob das wirklich durchdacht wurde.

Im Moment ist es doch so, dass man mehrere Kommentare zu ein und derselben Aufgabe abgeben kann, die sich auf verschiedene Dinge beziehen (siehe auch die verschiedenen Kategorien: Technisches/Inhaltliches/Gestaltung). Es ergibt also durchaus Sinn, dass man nicht den bereits abgegebenen Kommentar weiterbearbeitet.

Wenn trotzdem alles in einen Kommentar kommen soll, bräuchten wir die Kategorien und Prioritäten nicht mehr, weil die ja nicht mehr zuordenbar sind, wenn mehrere Issues in einem Review beinhaltet sind.

Alternativ sehe ich nur die Möglichkeit, dass man auswählt, ob man einen neuen Kommentar abgibt oder einen bestehenden ändern möchte. Letztes erfordert also auch die Anzeige einer Liste von bereits bestehenden Kommentaren.

Was ist hier also gewollt?
