### ISSUE TITLE
Reviews sollen UserAgent-Daten enthalten

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#438]
Außerdem interessieren uns für technische Rückmeldungen auch dringend vor allem Browser- (und Version) und ggf. Gerätespezifikationen. Sofern diese noch geloggt werden könnten (z. B. als JSON-String, wie auch bei den Testcenterlogs oder als separate Spalten), wäre das extrem hilfreich.

**Comment by franikowsp** [comment]
Ich müsste leider noch eine Anforderung draufsetzen: Bei Review-Kommentaren sollte, wenn möglich, die Seite erkennbar sein, auf die sich der Kommentar bezieht. Alternativ sollte eine Spezifikation des Bezugs möglich sein (also worauf sich der aktuelle Kommentar bezieht). In Deutsch setzen wir ja Aufgaben mit teilweise 10 Seiten um und die Kommentare könnten sich theoretisch auf jede einzelne Aufgabe beziehen.

**Comment by paflov** [comment]
Gut, ist aber ein extra Ticket wert: #440
