### ISSUE TITLE
Fehler beim Speichern schriftlicher Rechenaufgabe (Subtraktion)?

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#443]
Bei einer morgen startenden Präpilotierung (Testcenter **v14**) trat ein kritischer Fehler auf, der das Weiterkommen verhindert (auf **v15** tritt es nicht auf):
<img width="1491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1dBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8967f5e7528e4b84759425fe3601d12efa4adf7d/image.png" alt="image.png" />

Insgesamt scheinen sehr viele Errors bei schriftlichen Rechenaufgaben gemeldet zu werden beim Testcenter, aber nur auf dieser Aufgabe kommt es zum Abbruch. Gibt es die Möglichkeit, das noch irgendwie zu fixen?

Es ist zusätzlich eine Glühlampe mit Tooltip eingebunden (aber ich weiß nicht, ob das die Probleme verursacht). Der Fehler deutet für mich irgendwie auf ein Speicherproblem für Rechenkästchen hin?

**Comment by paflov** [comment]
Das ist der Grund, warum wir die alte Produktivinstanz endlich Plattmachen müssen. Die DB ist fünf Jahre alt und in einem falschen Zeichensatz kodiert, der bestimmte Sonderzeichen nicht erlaubt. Das lässt sich nicht im Nachhinein verhindern. Ich muss leider sagen, dass man hier nichts machen kann.
