### ISSUE TITLE
Testleitungskonsole: "Springe zu" soll Block wieder öffnen

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#447]
- **Problem:** Die "-> Springe zu"-Schaltfläche funktioniert nur, wenn ein Block noch nicht begonnen wurde (Szenario: zeitbeschränkte Blöcke).
   - Sofern man versucht eine Person auf (1) einen Block zu schieben, der bereits begonnen wurde, oder auf (2) einen Block, auf dem sie sich gerade befindet, (1) ist das nicht möglich bzw. (2) sperrt das sofortig den Block und ist ebenfalls nicht möglich.
- Die "Springe zu"-Schaltfläche sollte die Funktion erhalten, dass eine Person zum Beginn desjenigen Blocks, zu dem sie springen soll, gelangt und bei zeitbeschränkten Blöcken für diesen Block dann noch die Restzeit verfügbar hat.

**Comment by paflov** [comment]
- Für den Bug (1, Man wird auf einen Block navigiert auf dem man bereits ist) und dieser wird gesperrt habe ich einen Fix
(https://github.com/iqb-berlin/testcenter/commit/e56e4e76508145ec2345002a8af970789bf59300), der in die 15.1.0 kommt. 

- Das Feature Request (2, Navigation auf einen bereits zeitgesperrten Block und Restzeit wird wieder aufgenommen) kann ich erst mit der Version eine Lösung anbieten, die die Verzweigung enthält (voraussichtlich 15.2.0), in der die gesamte Restriktionen-Verwaltung überarbeitet ist. Augenblicklich wird die Restzeit nicht vorgehalten.

**Comment by paflov** [comment]
@franikowsp Es tut mir leid, aber ich kriege es in der Architektur der 15.1 einfach nicht hin. Es beim sperren des Blocks nicht die verbleibende Zeit verworfen sondern auch die Verbindung zwischen dem zeitbeschränkten Block und in den Units. In der 15.2 gibt es das quasi umsonst, ich werde es erst dann umsetzen. Eure kommende Studie muss ohne gehen.
Zur Beruhigung: Es sind schon viele Studien mit zeitbeschränktem Block gelaufen und mir ist ein Problem, wie ihr es antizipiert nicht untergekommen.

**Comment by franikowsp** [comment]
Okay, danke für die Rückmeldung. Der erste Fall sollte auch der wahrscheinlichere sein (der andere Fall ist aber nicht ausgeschlossen, da wir ja Medien und Sichtbarkeitseinstellungen haben, die es notwendig machen, überhaupt in der TL-Konsole einzugreifen).
