### ISSUE TITLE
Aktuelle Chrome Version wird nicht als aktuell bewertet

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/testcenter#448]
<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bf8d30701817aed92a38d1aa5b7c6349e9a181d/Screenshot%20from%202024-02-28%2010-20-56.png" alt="Screenshot from 2024-02-28 10-20-56.png" />

**Comment by paflov** [comment]
Dublikat zu #434
