### ISSUE TITLE
Loginseite: Enter-Taste führt zu Passwortfeldfokus statt dem Abschicken des Formulars

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter#453]

**Comment by paflov** [comment]
Mir ist gerade durch Zufall aufgefallen, dass bei mir (TC15, FF oder Chrome) enter sehr wohl zum Abschicken des Formulars führt? Was ist bei dir anders?

**Comment by rhenck** [comment]
Kann eigentlich nicht sein. Hier die Codestelle:
https://github.com/iqb-berlin/testcenter/blob/899138964505e1491cf6b9fafdd5fdb3d648ab15/frontend/src/app/app-root/login/login.component.html#L16
