### ISSUE TITLE
Testcenter Modus Interaktives Übungsmodul

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/testcenter#454]
Lieber Philipp,

wir wollen für die BiSta-Pilotierung ein interaktives Übungsmodul auf die Webseite stellen. Dafür brauchen wir also einen Testmodus der keine Antworten und Logs abspeichert, aber trotzdem alle Navigationsbeschränkungen aus dem Booklet anwendet (es geht vor allem um "presentation complete"-Beschränkungen).

Könntest du den "Run-Demo"-Modus zu diesem Zwecke abändern? Bisher gibt es noch keinen Modus der das kann und der "Run-Demo"-Modus schien uns dafür am geeignetsten?

@Martin Wir hatten ja kurz im JF darüber geredet, du warst damit einverstanden?

Bei Fragen melde dich gerne bei mir.

Vielen Dank schon mal und viele Grüße
Jakob

**Comment by paflov** [comment]
Beschluss TCJF: Neuer Modus muss her. Alle Restriktionen greifen, kein speichern.
