### ISSUE TITLE
Responses und Logs: alias fehlt

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#457]

**Comment by franikowsp** [comment]
Ah, ich sehe gerade: Der `unitname` wird dann aus dem `alias` belegt. Wäre es dann aber nicht sinnvoll, die Unit-`id` noch irgendwo im Output mitzuführen? `unitname` wäre vielleicht die `id` `unitname` wäre dann der `alias` oder die `id` bei fehlendem Alias?

**Comment by paflov** [comment]
ursprüngliche zusätzliche spalte mit Unitid kann hinzugefügrt werden. Die urpsüngliche sollte wegen kompatibilität so bleiben wie sie ist.

**Comment by paflov** [comment]
Hier gehts um Antwortdaten und Logs, nicht (nur) reviews.
