### ISSUE TITLE
BrowserslistError auf Login Seite

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/testcenter#458]
# Fehlerbeschreibung

Beim Aufruf der Login-Seite (http://localhost/#/r/login/) wird die folgende Fehlermeldung angezeigt:

```
Fehlerbericht: Programmfehler: BrowserslistError

Unknown version 121 of chrome


Zeitpunkt: Mar 14, 2024, 8:51:53 AM

Url: http://localhost/#/r/login/

Browser: Firefox 123.0

Betriebssystem: Ubuntu

Gerät: 
```

# Kontext
**Server**: Docker dev

**Frontend-Version**: master

**Backend-Version**: master

**Testdaten (player etc.)**: -

**URL**: http://localhost/#/r/login/

**Modus**: -

**Browser**: Firefox 123 (Snap)

**Betriebssystem**: Ubuntu 23.10 

# Screenshot

![grafik](https://github.com/iqb-berlin/testcenter/assets/9805083/6847eb4b-5303-41b7-b0b6-142e30b80bb0)

**Comment by ojauch** [comment]
Ich habe gerade die Version mal auf 15.0.0-rc9 gedowngraded und dort tritt das Problem so nicht auf.

**Comment by paflov** [comment]
Ist in den 15.1ern auch gefixed.
