### ISSUE TITLE
Test lädt nicht

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/testcenter#459]
# Fehlerbeschreibung

Bei der Anmeldung als Testuser und der Auswahl eines Booklets wird der Test beim ersten Versuch nicht geladen. Das Laden bricht bei 22,22 % ab und der Browsertab hängt sich auf. Firefox zeigt dann "Diese Seite verlangsamt Firefox ..." an und bietet an den Tab anzuhalten. Erst nach dem Anhalten ist ein Neuladen der Seite möglich. Wenn man die Seite danach neu lädt, wird der Test richtig geladen.

# Kontext
**Server**: Local Docker Dev

**Frontend-Version**: master

**Backend-Version**: master

**Testdaten (player etc.)**: BOOKLET.SAMPLE-1 (Testdaten)

**URL**: http://localhost/#/t/1/status

**Modus**:

**Browser**: Firefox 123.0.1 (Snap)

**Betriebssystem**: Ubuntu 23.10

# Screenshot

![grafik](https://github.com/iqb-berlin/testcenter/assets/9805083/3aaf26f1-3df7-4989-8a7e-083376cbbad0)

**Comment by paflov** [comment]
Tritt bei mir nicht auf, wurde aber vom Kollegen ebenfalls berichtet, dass es manchmal passiert. Bin für jeden Hinweis dankbar.

**Comment by ojauch** [comment]
Danke für die Rückmeldung. Ich habe gerade die Version mal auf 15.0.0-rc9 gedowngraded und dort tritt das Problem so nicht auf.

**Comment by huaning-yang** [comment]
Also der Fehler bei mir auftrat hat mir die Konsole folgendes ausgegeben:
![Screenshot from 2024-03-18 13-46-10](https://github.com/iqb-berlin/testcenter/assets/78593320/1b4648d5-5c6a-4edf-bae1-e2d6b4db041c)
Kann das konsistent erzeugen in dem ich die volumes komplett lösche und beim ersten Laden eines booklets kommt es zu diesem Fehler. in einem neuen Tab werden dann alle booklets normal geladen

**Comment by rhenck** [comment]
Scheint unabhängig vom Player zu sein. Ich habe das gleiche Verhalten mit dem speedtest-player.
