### ISSUE TITLE
Fehlende HTTP - Security - Kopfzeilen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#47]
Aus Penetrationstest IBBW v0.7 [H_04]

Security Header fehlen:
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff

https://owasp.org/www-project-secure-headers/

**Comment by paflov** [comment]
Wurde im PenTest Bayern (S3) auch noch mal dringend empfohlen. Sollten wir noch einmal diskutieren.

**Comment by rhenck** [comment]
Das ist alles bereits erledigt. Siehe docker-compose.prod.tls.yml

**Comment by paflov** [comment]
Ah, stimmt, sehr gut!
