### ISSUE TITLE
Backend: Cannot create workspace dir

### ISSUE THREAD

**Issue by D31nH31mbrau3r** [iqb-berlin/testcenter#477]
# Fehlerbeschreibung hängt zusammen mit #476 
und https://github.com/iqb-berlin/testcenter/commit/6d233cb29ce3a49040e3dfdfc7fde8349fd66fe3

Das Anlegen eines Workspaces im Administratoren-Bereichs gelingt, jedoch sobald man in den Arbeitsbereich wechselt, kommt unten stehende Fehlermeldung und man kann auch keine Dateien hochladen, da kein Arbeitsbereich angelegt werden kann. Ein Upload in schon bestehende Arbeitsbereiche gelingt auch nicht mehr mit der Fehlermeldung "Upload target path is not writable"

Allgemeines Server-Problem.
Error-Id: error-660c2417b869d5.27944025
Es ist ein Programmfehler aufgetreten. Laden Sie die Seite neu und probieren es noch einmal. Sollte das Problem weiterhin bestehen bleiben, melden Sie es dem zuständigen Systemadministrator.
Fehlerbericht: Allgemeines Server-Problem.

Could not create workspace dir 2

Http failure response for .../api/workspace/2/files: 500 OK

Error-Id: error-660c2417b869d5.27944025

Zeitpunkt: Apr 2, 2024, 5:28:23 PM

Url: .../#/admin/2/files

Browser: Firefox 124.0

Betriebssystem: Windows 10

Server-Version: 15.1.0

**Comment by D31nH31mbrau3r** [comment]
Zusatz der server log gibt folgendes aus: 

error-660c2417b869d5.27944025 (500) `Could not create workspace dir 2` at /var/www/backend/src/workspace/Workspace.class.php:42

**Comment by paflov** [comment]
Danke für den Hinweis, das ist natürlich eine peinliche Sache. Ist behoben in Testcenter 15.1.3. 

Der Zusammenhang zu #476 ist ganz richtig vermutet - wir hatten probiert den Backend-Container als anderen user als root laufern zu lassen aus Sicherheitsgründen. Nachdem das nicht ganz geklappt hat, haben wir es (erstmal) zurückgebaut und dabei etwas übersehen. Eine fiese Sache, da das Problem in der Entwicklungsumgebung in der etwas anderen Umgebung der automatischen Tests nicht auftritt, sondern wirklich nur in prod.
