### ISSUE TITLE
Anmeldung funktioniert ab und zu nicht

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#479]
# Fehlerbeschreibung

Wenn ich mich neu anmelde, kommt immer die Fehlermeldung (siehe Screenshot) und danach kann ich manchmal gar nicht mehr meine Anmeldedaten (Name und Kennwort - quasi nicht mehr beschreibbar) ändern. Dafür muss ich die Seite neu laden (und es kommt wieder derselbe Fehlerbericht), danach geht es wieder.

```
Fehlerbericht: Programmfehler: TypeError

f.getModifierState is not a function







Zeitpunkt: Apr 3, 2024, 4:07:27 PM

Url: https://iqb-testcenter2.de/#/r/login/

Browser: Chrome 123.0.0.0

Betriebssystem: Windows 10

Gerät:
```

# Kontext
**Server**: https://iqb-testcenter2.de/#/r/starter

**Testdaten (player etc.)**: 4.6.7

**URL**: https://iqb-testcenter2.de/#/r/starter

**Modus**: (bereits für Admin, aber auch für Testpersonen)

**Browser**: Firefox Chrome

# Screenshot
![Image20240404093811](https://github.com/iqb-berlin/testcenter/assets/60889089/0d7b25c8-9411-4a0c-a51f-35512e08d34d)

**Comment by paflov** [comment]
Selbe Fehlermeldung wie hier: https://github.com/iqb-berlin/testcenter/issues/481
Schient nur ganz neue Chomebased-Browser zu betreffen!

**Comment by paflov** [comment]
Hängt eindeutig mit der Prüfung der Feststelltaste zusammen. Ist eindeutig das gleiche Problem, das mit der Prüfung der Feststelltaste in ganz neuen Chrome-based Browsern verursacht wird (#481). Das Problem ist gar nicht so sehr die neuanmeldung, sondern dass von der vorherigen Anmeldung Zugangsdaten im Feld gespeichert sind.
