### ISSUE TITLE
Units werden nach Abbruch eines Testhefts nicht mehr gefunden

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#480]
# Fehlerbeschreibung

Es werden nach Abbruch eines Testheftes Units nicht mehr gefunden, obwohl die Testteile vorher noch durchklickbar waren. Das schien insbesondere zeitbeschränkte Blöcke zu betreffen (bei den Instruktionen schien kein Problem zu bestehen - diese sind nicht als `Testlet` angelegt).

Leider habe ich mir nun alle Testhefte weggeschossen

# Kontext
**Server**: https://iqb-testcenter2.de/#/r/starter

**Testdaten (player etc.)**: 2.4.7

**URL**: https://iqb-testcenter2.de/#/r/starter

**Modus**: `run-hot-return`

**Browser**: Chrome

# Screenshot
![Image20240404094319](https://github.com/iqb-berlin/testcenter/assets/60889089/d3ad9d2c-1507-49ae-93ad-663a938160b5)

**Comment by franikowsp** [comment]
Update: Wenn man beim Abbruch-Dialog auf "Trotzdem weiter" klickt, wird der Teil trotzdem unterbrochen und der Fehler tritt auf.

**Comment by paflov** [comment]
Dieses Problem ist weniger allgemeingültig als es zunächst den Anschien hat: Es tritt nur auf wenn man die (informelle) Regel nicht beachtet, keine Intro- oder Outrounit im Bookelt zu haben (also mindestens eine Unit am Anfang und eine am Ende, die nicht Teil eines Testlets ist). 

(Ein Fix folgt trotzdem gleich, ich protokolliere nur, weil die Tickets auch zunehmend von verschiedenen Nutzern gelesen werden.)
