### ISSUE TITLE
Globale CustomTexts greifen nicht mehr

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#482]
# Fehlerbeschreibung

Beispiele (es sind nicht alle betroffen; für den Bug-Report #480 und den damit verbundenen Zugang habe ich das als lokalen `CustomText` überschrieben, sodass es dort richtig aussieht):

![Image20240404095916](https://github.com/iqb-berlin/testcenter/assets/60889089/5f311d4a-af38-439d-81ba-92626e6e7091)

![Image20240404095957](https://github.com/iqb-berlin/testcenter/assets/60889089/91187eff-430b-4bd1-b939-401cdf0bf09e)

# Kontext
**Server**: https://iqb-testcenter2.de/#/r/login/

**Comment by paflov** [comment]
Sie greifen, schon, allerdings erst nach einem Neuladen. Teilnehmer würden also den CustomText auf jeden Fall sehen.
