### ISSUE TITLE
PresentationComplete wird erst nach Neuladen der Unit mit veralteter Player Version korrekt erkannt

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#493]
# Fehlerbeschreibung

IBBW meldet unterschiedliches Verhalten von presentation complete bei TC V15 und TC V14.
2 Fehler haben wir dsbzgl.:

1. Habe dir per Mail Testdateien geschickt. Bei diesem Test wird bei der ersten Aufgabe (Start) presentation complete ignoriert, es kann weitergeblättert werden obwohl nicht alles auf dem Bildschirm ist. Dies scheint aber bei beiden TC-Versionen so zu sein.
2. V15: Wenn man sich im Block befindet und den Test beendet und anschließend fortsetzt, kann man nicht mehr vorwärts blättern wegen presentation complete. Der Test kann auch nicht mehr verlassen werden. Bei V14 ist das nicht so.

**Comment by paflov** [comment]
Es handelt sich hierbei um ein äußerst komplexes Zusammenspiel von verschiedenen kleineren Bugs und Faktoren.

# Fehlverhalten Testcenter
Bug 1) Mit Verona vier wurde das automatische Melden von Zuständen (`stateReportPolicy: 'eager'`) - etwa `presentationProgress` - zum Standard. Das Testcenter setzt diesen Modus folgerichtig nicht mehr explizit. Einige sehr alte Player (z. B. der hier verwendete *Aspect 1.20.1*), melden standartmäßig die Zustände aber nicht - und melden, da sie nicht mehr explizit dazu aufgefordert werden einfach gar nichts. 
Bug 2) Wenn der `presentationProgress` nie gesetzt wurde, ignoriert das Testcenter `force_presentation_complete` - man kann weiter navigieren ohne alles gesehen zu haben. Bei Neuladen der Unit wird der `presentationProgress` als `NONE ` initialisiert. Durch Bug 1 wird dies nie überschrieben, auch wenn man nach unten scrollt. Man kann nicht weiter navigieren, egal was man tut. Dieses Verhalten war in TC14 genau dasselbe, dazu kam es jedoch nie, da Bug 1 nicht auftrat.
 
# Weitere Faktoren
Faktor 3) Man kann in der Tat den Test auch nicht beenden, wenn `force_presentation_complete` gesetzt und die unit nich vollständig angezeigt ist. Meines Wissens ist das so gewollt.
Faktor 4) Die Unit (L5M_Start) ist so gestaltet, dass sie bereits `presentationProgress` als `complete` sendet, wenn alle sechs Pfeile zu sehen sind, auch wenn der Text darunter nicht zu sehen ist.
