### ISSUE TITLE
V15.01: Verbindungsfehler Teststart

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#496]
# Was passiert?

Ein run-hot-return Test bricht beim Laden (TC-Server 4 mit TC-Version 15.01) mit folgender Meldung ab:

![Screenshot from 2024-04-17 08-58-43](https://github.com/iqb-berlin/testcenter/assets/78656991/2e85971a-ddd8-4c8d-8740-02a6bdb0ffd1)

# Wo passiert es?

Windows: 
* Firefox 124 **Test läuft nicht**
* Edge 122 **Test läuft nicht**
* Chrome 24 **Test läuft nicht**

Linux:
* Edge 122 **Test läuft nicht**
* Firefox 124 Test läuft
* Chrome 122 Test läuft

**Comment by huaning-yang** [comment]
Interessant dass sie bei der mit unterschiedlichen Browsern funktionieren.
Bei mir erscheint der Bug unter Windows als auch Linux bei allen Browsern

**Comment by huaning-yang** [comment]
Es lag an dem www in der Adressleiste.
Problem ist mit Version 15.1.0 gefixed (commit 0031b67f29c99533529b63c13ecb671411d240b0)
