### ISSUE TITLE
Review Kommentare: Datenfelder CSV-Datei nicht eindeutig

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#502]
**V15.2**
Irgendwie sieht die CSV komisch aus oder ich checks nicht.
Schau mal hier der gegebene Kommentar:

![Screenshot from 2024-04-19 12-38-27](https://github.com/iqb-berlin/testcenter/assets/78656991/42945305-de3e-4d6e-bed2-b1cf78832ee2)

Und hier die erzeugte CSV:

![Screenshot from 2024-04-19 12-40-29](https://github.com/iqb-berlin/testcenter/assets/78656991/d8fc7ba1-8dde-4305-9ed1-9e9e4d7a54fa)

Hier steht einmal **category** und einmal **category: content**. Unter beiden steht ein **X**

**Comment by paflov** [comment]
Siehe auch: #439
