### ISSUE TITLE
Ipad: Websocket Connection failed

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#504]
Folgeticket von [#500](https://app.zenhub.com/workspaces/testcenter-62626b86ce834f001598ef86/issues/gh/iqb-berlin/testcenter/500)

Bug:
- im Testcenter 2
- Man kann sich auf dem Ipad (getestet auf IOS 15.3.1 und 15.6) erfolgreich als Schüler einloggen. Wenn jedoch ein Booklet ausgesucht wird, gibt es einen Websocket Error
![grafik](https://github.com/iqb-berlin/testcenter/assets/60889089/02e8b98e-ca8e-4b69-8fe8-3ebdab32c5bd)
- Error erscheint nicht auf Desktop oder neueren Iphone (IOS 17.4.1). Nur auf getesteten Ipad (IOS 15.3.1 und 15.6)

**Comment by paflov** [comment]
Hier kommen folgende Dinge Zusammen:
1. iPads 15x melden beim etablieren der Websocket-Verbindung eine Verletzung der CSP.
2. Das Umschalten auf Polling funktioniert nicht, stattdessen kommt dieser Fehler.

**Comment by paflov** [comment]
Der kritische Part von 2. wurde erledigt, damit sollte auch 1. kein Problem sein - iPads 15 sollten nun auf polling umschwenken können. Gerade habe ich keine Möglichkeit zum testen.

es verbleibt: #510
