### ISSUE TITLE
SysCheck Beispieldaten sinnvoller gestalten!

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#51]

**Comment by paflov** [comment]
Der Beispiel-Systemtest ist wenig Sinnvoll gestaltet.
Das betrifft vor allem:
- Den Fragebogen in dem Unsinn steht
- Die mitgelieferte Unit ist schlecht (besonders, da sie versucht, eine externe Resource nachzuladen, was im Kontext des SysChecks gar nicht geht) Siehe #239 .

**Comment by huaning-yang** [comment]
Haben wir eine Beispiel Unit die nicht das Problem mit den externen Ressourcen hat?
Arbeite im Moment an #240, aber kann meine Änderungen ohne eine richtige Unit nur schwer testen
