### ISSUE TITLE
Delete File API Endpoint Internal Server Error

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/testcenter#529]
# Fehlerbeschreibung

Wenn ich auf den [delete files](https://pages.cms.hu-berlin.de/iqb/testcenter/dist/api/index.html#tag/admin-workspace/paths/~1workspace~1{ws_id}~1files/delete) Endpunkt der API mit der folgenden Anfrage zugreife, erhalte ich eine 500 Internal Server Error Antwort:

```
curl -H "AuthToken: $AUTH_TOKEN" -X DELETE --data '{"f": ["testtakers-test-klasse.xml"]}' -i 'http://localhost/api/workspace/1/files'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: SubscribeURI, Error-ID
Content-Length: 217
Content-Type: text/html;charset=UTF-8
Date: Tue, 07 May 2024 11:57:15 GMT
Error-Id: error-663a171b657580.00159370
Referrer-Policy: no-referrer
Server: Apache
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 23 (fetchFiles)
```

Die angegebene Datei wird nicht gelöscht. Das erwartete Verhalten wäre eine 2XX Antwort zu erhalten und dass die Datei anschließend gelöscht ist.

# Kontext
**Server**: Lokal dev

**Backend-Version**: 15.1.5

**Comment by paflov** [comment]
Hi, in der Dateiliste muss "Testtakers/testtakers-test-klasse.xml" stehen (also mit Typ bzw. Ordner vor dem Dateinamen) , damit die Datei gefunden werden kann.
Ein SQL-Fehler ist trotzdem Fehlverhalten natürlich! Eigentlich sollte bei nicht vorhandenen Dateien ein 207er zurück kommen mit folgendem Inhalt:
```
{
"deleted": [],
"did_not_exist": ["testtakers-test-klasse.xml"],
"not_allowed": [],
"was_used": []
}
```

Da einem das über die GUI nicht passieren kann, stufe ich diesen Bug aber erstmal als nicht so ganz dringend ein.

**Comment by ojauch** [comment]
@paflov Vielen Dank für die Rückmeldung! Den Dateityp ergänze ich in unserer Logik und dann stellt das für uns auch erstmal kein Problem dar.
