### ISSUE TITLE
Verändern der Gruppen-ID führt zu Fehler

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#530]
Reproduktion:

1. Testtaker.xml enthält Login XYZ in Grupe ABC
2. Login als XYZ
2. Testtaker.xml löschen
3. TesttakerNEU.xml enthält Login XYZ in Gruppe DEF
4. Login als XYZ 
 FEHLER! 

Could not retrieve group token for `DEF`.

**Comment by nam-du-iqb** [comment]
closed in: #768
