### ISSUE TITLE
System-Check Probleme bei mehrfacher Durchführung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#542]
### Nach SC Neustart stellenweise kein Weiterblättern durch den Check möglich

Wurde bereits ein Bericht erzeugt und soll der Check ein zweites Mal durchgeführt werden, kann manchmal erst im Check weitergeblättert werden, wenn zuvor die Anmeldeseite mit dem SM-Schalter neu geladen wurde.

**Comment by nam-du-iqb** [comment]
scheint nur auf TC3 aufzutreten.

Beschreibung:
- ein System Test wird ausgeführt 
- die Navigation daraufhin funktioniert wie geplant
- wenn man dann über das Logo auf die Hauptseite zurücknavigiert und erneut einen system-check ausführen möchte
  - dann kann es sein, dass man nicht mehr über das Netzwerk Tab hinauskommt

Man muss das Browsertab mit Hard Reloading aufrufen, um einen weiteren Test durchführen zu können.
