### ISSUE TITLE
System-Check: Dateiname nicht Root-Element ist entscheidend zum Starten

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#545]
Der System-Check Schalter erscheint erst, wenn die System-Check-XML auch tatsächlich **SysCheck.xml** heißt. Es ist hier also nicht das Root-Element `<SysCheck>`ausschlaggebend. Soll das so sein?

**Comment by paflov** [comment]
Ja, kann ich bestätigen.
