### ISSUE TITLE
System-Check: Keine Prüfung von angelegten Aufgaben beim Laden

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#546]
Wird eine System-Check-XML mit einer deklarierten Aufgabe in das Testcenter geladen, findet keine Prüfung statt, ob die Aufgaben-XML bereits im Testcenter ist. Die fehende Aufgabe wird erst nach Start des System-Checks bemerkt, erst dann erscheint eine Fehlermeldung.

**Comment by paflov** [comment]
Dublikat: https://github.com/iqb-berlin/testcenter/issues/424
