### ISSUE TITLE
Passwort von Admins beim erstmaligen Login muss geändert werden

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#586]

**Comment by mechtelm** [comment]
* Menüpunkt "neu anmelden" ändern in Icon "Person" analog iqb-studio mit zwei Menüpunkten "Kennwort ändern" und "Abmelden" - auch mit mat-icons und tooltips
* "erstmaliges Login" trifft's nicht genau. Es muss in der User-Tabelle ein neuer boolscher Wert `pw_set_by_admin` oder so anzeigen, dass der Superadmin das Kennwort gesetzt hat. Das trifft auch zu bei "Kennwort vergessen", d. h. der Superadmin setzt auf Bitte des Users ein neues Kennwort
* Das Redirect nach dem Login ist im Fall "Kennwort ändern erzwingen" etwas schwierig. Das alte redirect-Ziel müsste erhalten bleiben.
