### ISSUE TITLE
GM: Vorkonfigurierte Ansicht & Filter

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#589]
## SOLL:

1. In der TT-Datei sollte eine Ansicht vor konfigurierbar sein, also welche Ansichtsoptionen Standard sind.
2. Jede Spalte sollte nach Strings filterbar sein. Auch diese Filter müsste vor konfigurierbar sein.

**Comment by tobhu1981** [comment]
# Rückmeldung zur aktuell laufenden Version auf Testserver 15.3.0-alpha

## Generell

* Ist wahrscheinlich nen altes Ding: Ansicht ungünstig. Spalte **Aufgabe** wird nicht richtig angezeigt, wenn alle Spalten oder vollständige Aktivität angezeigt werden. Zeile für Zahnrad und Lupe müsste vielleicht höher/breiter sein. Siehe Bild:
![1](https://github.com/user-attachments/assets/c4b5bfd8-2b2e-4efc-a9d8-d15e32b4d87e)
* Was bedeutet die 21 bei alias (siehe Bild) ![3](https://github.com/user-attachments/assets/169cd315-1e1d-4078-901b-54353047a248)

### Neue Filtermöglichkeit

* Feldgröße Anzeige festgelegte Filter müsste sich dynamisch danach richten, ob der Haken vor dem Filter gesetzt wird, da das sonst seltsam aussieht (siehe Bild) 
![2](https://github.com/user-attachments/assets/7c86a267-ff1a-4929-b4d9-c73e32c2b747)
* "heraus gefiltert" wird das nicht zusammen geschrieben?
* Nice to have: Warum Schalter für erweiteter Modus ganz unten? Könnte man den auch höher platzieren bspw. rechts neben dem Formularnamen: "Neuen Filter Hinzufügen"? Hier fällt mir grad auf müsste "Hinzugügen" klein geschrieben werden:-)
* In den Filtereinstellungen muss der Schalter: **Nicht** gesetzt werden, damit der Filter funktioniert. Abfrage **Nicht** scheint fehlerhaft.
* Wie können angelegte Filter wieder gelöscht werden? Oder ist nur vorgesehen bestehende neu anzupassen und somit keine weiteren Filter erzeugen zu müssen?

**Comment by tobhu1981** [comment]
**Not** in Filtervorbelegung in TT hat immer noch  keine Auswirkung.
