### ISSUE TITLE
Brute Force Angriff auf Login - Maske möglich

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#59]
Aus: Penetrationstest IBBW v0.7

> Die  Webanwendung  bietet  keinen  Schutz  vor  Brute-Force  Angriffen.  Einem 
> Angreifer ist es somit möglich beliebig viele Kombinationen aus 
> Benutzername und Passwort auszuprobieren.

> Es  wurden  für  den  Benutzer pentest.lehrer1.mit über  3.000  bewusst  fehlerhafte Login-Versuche probiert. Der Login war nach dem Angriff weiterhin mit dem richtigen Passwort möglich

> Das    wiederholte    Aufrufen    der    Login-Funktion    sollte    begrenzt    werden. Beispielsweise   wäre   der   Einsatz   von   sogenannten   Teergruben   oder   von CAPTCHAs   möglich.   Auch wäre   es   denkbar,   Accounts   nach   mehreren fehlgeschlagenen  Versuchen  temporär  zu  sperren.

https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks

**Comment by rhenck** [comment]
Hier können wir tarpitting oder captchas machen. Denke mal, wenn überhaupt kommt tarpitting in Frage. Das müsste aber in der Software implementiert werden. Da gibts keinen easy-fix.

**Comment by paflov** [comment]
Wurde im PenTest Bayern auch noch mal angemeckert. (L1). Hier sollten wir dringend eine Lösung finden.

**Comment by paflov** [comment]
mögliche Apache mods durchprobiert, Lösung mit shmop angedacht. Erstmal zurückgestellt, denn sollten wir bald Redis haben, lässt es sich wesentlich besser damit lösen.

**Comment by paflov** [comment]
Wieder kritisiert im Pentest Bayern 14.5.24 (2.4)

> Es muss ein Schutz gegen Brute-Force-Attacken auf das Anmeldeformular implementiert werden. Dies kann beispielsweise eine Sperrung des Benutzerkontos, eine Sperrung der IP-Adresse des Angreifers für den Zugriff auf die Anwendung
> oder eine künstliche Verlangsamung der Verarbeitung von Anmeldeversuchen nach einer bestimmten Anzahl an fehlge-
> schlagenen Anmeldungen sein.

**Comment by paflov** [comment]
Absprache mit MM: Lediglich bei der Admin-Anmeldung (putSessionAdmin in SessionController.class.php" musss ein kleiner Timeout gesetzt werden um hier Bruteforce-Angriffe zu vereiteln.
