### ISSUE TITLE
Demo-Review-Mode: Anzeige der Info beim Weiterblättern

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#60]
Wird eine Aufgabe vollständig ausgefüllt und werden alle Medien abgespielt, erscheint beim Weiterblättern zur nächsten Unit trotzdem die Meldung, dass hier normalerweise nicht weitergeblättert werden dürfte, da noch nicht alles ausgefüllt ist. Es ist ja nur ein Demo-Mode, daher bin ich mir nicht sicher, ob die Info in einem solchen Fall nicht kommen sollte oder ob man das Verhalten so belässt.

**Comment by huaning-yang** [comment]
@tobhu1981 könntest du mir Beispiel unit/booklet/testaker Dateien geben die diesen Fehler erzeugen?
Ich kann das mit den standard sample booklets/units Sachen leider nicht reproduzieren und mir fehlt dass Wissen um die so eine Aufgabe zu designen.

**Comment by tobhu1981** [comment]
Mit welcher Version auch immer sich das erledigt hat......es hat sich scheinbar erledigt. Habe gerade noch einmal mit einem Demo Booklet getestet und die Meldung erscheint nicht, wenn entsprechende Pflichtfelder ausgefüllt wurden. @Huaning: Machst du das Ticket zu?
