### ISSUE TITLE
Test_logs fehlen in der log-Ausgabe?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#601]
In der Log-Ausgabe (sowohl CSV als auch JSON) erscheinen (anscheinend?) anktuell nur die logs aus unit_logs, nicht die aus test_logs. Falls das stimmt, wäre es dringlich zu fixen.

**Comment by nam-du-iqb** [comment]
Problem kann nicht festgestellt werden. Sowohl CSV als auch JSON geben die Unit-Logs und die Test-Logs aus. Wird vorerst geschlossen, bis das Problem näher beschrieben werden kann.

CSV:
[iqb-testcenter-logs(4).csv](https://github.com/user-attachments/files/17278072/iqb-testcenter-logs.4.csv)
JSON:
[logs.json](https://github.com/user-attachments/files/17278108/logs.json)
