### ISSUE TITLE
Syscheck soll LoginInformationen aus Testtaker für Authorisierung nutzen

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#602]
## Finale Version:

Soll in Version 15.3 umgesetzt werden

## Beschreibung:

- syscheck type in testtaker soll auch mit name, pw, und code geschützt werden können
- wenn der Link tc.de/<syscheckid> aufgerufen wird, dann springt man direkt in der Syscheck
- "Durchschreiben" von logininfos für das Absenden von SysCheck Reports
-- savekey kann gestrichen werden
-- schulid ist jetzt loginname + code
- nach Absclhuss des Reports, automatische Umleitung auf die Starter Seite
- "responses" sollen mit in die syscheckReports inkludiert werden (eine weitere Spalte im CSV / Feld im JSON)
- 
### Version:15.3.0alpha3

**Comment by tobhu1981** [comment]
Folgendes ist bisher augefallen:
- nach Anmeldung SC erscheint ein Fenster mit Geräteinformationen. Links davon sind noch Instruktionen zu sehen. Hier muss der Text bzgl. Speicherung am Ende raus
- es sind zwei SC-logins vorhanden, nach Durchführung mit dem ersten Login wird eine Durchführung mit dem 2.Login gestartet. Hier hätte ich erwartet, dass der SC bspw. beim Netzwerkscan automatisch neu startet und nicht der Button: "Neu starten" gedrückt werden muss
- soll ein SC-Bericht im AB gelöscht werden, kommt beim ersten Löschversuch eine Fehlermeldung, wird diese quittiert und es wird erneut versucht zu löschen kommt keine Meldung mehr, man muss aber die Seite neu laden, damit der Bericht nicht mehr in der Liste erscheint. Hier bin ich nicht sicher, ob das überhaupt was mit dem neuen Feature zu tun hat
- meldet man sich ein 2-mal mit dem gleichen Login an und startet den Netzwerkscan neu, ist es bei mir schon vorgekommen, dass es nicht weitergeht, es kann zwar auf den Vorwärtsbutton geklickt werden, es passiert aber nichts. Wird der Scan nicht neu gestartet, scheint es immer weiter zu gehen. Hier muss ich nochmal prüfen, ob das so reproduzierbar ist
- 
- 
-

**Comment by nam-du-iqb** [comment]
"Wird das Passwort in der SC-XML entfernt, kommt man nach dem Fragebogen nicht mehr weiter zum Bericht speichern Dialog. Der Vorwärtsbutton ist inaktiv. Die Anmeldung ist via SC-Login in der TT erfolgt"

Dies ist wird nicht gefixt, sondern sollte dokumentiert und kommuniziert werden, dass ein Passwort immer anzugeben ist. Dies stellt sicher, dass derselbe SC sowohl in der neuen als auch in der alten Navigation funktioniert.

**Comment by nam-du-iqb** [comment]
"Nach löschen der beiden SC-Logins in TT erscheint kein SC-Schalter in der Anmeldung, obwohl 3 SC-XMLs im TC sind"

Wurden alle SC-Logins aus allen TT gelöscht? Diese dürfen auf der ganzen TC Instanz nicht vorkommen. Dies muss dokumentiert werden.

**Comment by tobhu1981** [comment]
"Wurden alle SC-Logins aus allen TT gelöscht? Diese dürfen auf der ganzen TC Instanz nicht vorkommen. Dies muss dokumentiert werden."

Ja es wurden alle gelöscht.
