### ISSUE TITLE
[DEV] Bessere Logs beim initialize.php script

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#628]

**Comment by nam-du-iqb** [comment]
Wenn beim initialize.php eine fehlerhafte Resource (zb Testtakers) angegeben wird, können die Daten nicht korrekt in die DB persistiert werden. Man wird daraufhin jedoch nicht hingewiesen. Hier besseres Feedback für fehlerhafte Dateien.

**Comment by paflov** [comment]
`Workspace `ws 1 [restored 2024-10-10 14:51:09]`
Logins updated: -0 / +0
Files found: Resource: 4, Unit: 2, Booklet: 3, Testtakers: 1, SysCheck: 1
Processing time: 0.12420892715454 sec.
Invalid files found: 2
`

Letzte Zeile? Oder meinst du, es sollte auch genau geloggt werden, welche Datei? Habe ich auch schon mal drüber nachgedacht.
