### ISSUE TITLE
Testtakers: Das Ändern von GroupIDs ist nicht möglich, wenn die Login Names gleich bleiben

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#637]
IST: Nachdem eine Testtakers hochgeladen wurde und eine login_session erstellt wurde, kann für den selben LoginNamen keine neue GroupID erstellt werden, auch wenn die alte Testtakers gelöscht oder überschrieben wurde

SOLL: Der Workflow und die Beziehung zwischen Login und GroupId muss nochmal bedacht und überprüft werden.
- [x]  gruppe bleibt - login ändert sich
- [x]  gruppe bleibt - login kommt hinzu
- [x]  gruppe bleibt - login gelöscht
- [ ]  login bleibt - gruppe ändert sich (BUG!)
- [x]  login bleibt - gruppe kommt dazu

WARUM: Das System sollte dem entsprechen, was erwartet wird.

**Comment by paflov** [comment]
closed in: https://github.com/iqb-berlin/testcenter/pull/768
