### ISSUE TITLE
run-review/demo: Zeit startet neu bei Weiterblättern

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#64]
Testcenter version 12.1.0@12.2.2
TH: Befindet man sich einem zeitbeschränkten Block und lässt die Zeit herunterlaufen und blättert anschließend in die nächste Unit, startet die Zeit vor vorne.

**Comment by paflov** [comment]
Was sollte denn sonst passieren?
`unit_show_time_left=ON` und `demo` mode heißt ja, die Zeit soll angezeigt werden, aber nicht ernsthaft beschränken. Wenn sie also abgelaufen ist, soll man trotzdem weiter machen dürfen. OK, wäre vielleicht schöner, sie würde einfach auf 0 stehen bleiben, oder was meinst du?
