### ISSUE TITLE
Workspace-Admin: Upload Testdateien: Ok-Button während Upload

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#67]
Werden größere Testdateien in das Testcenter geladen, wird während der Ladezeit der OK-Button angezeigt. Wird dieser während eines noch nicht abgeschlossenen Uploads betätigt, wird der Upload scheinbar unterbrochen. Ist nicht besonders wichtig, aber ist der Button an dieser Stelle sinnvoll? OK-Button, noch dazu in grün, werden gerne einfach mal angeklickt :-)

**Comment by huaning-yang** [comment]
@tobhu1981 Könntest du mir mal die Testdateien schicken die du benutzt hast? Bei meinen Versuchen hat es geklappt, aber würde es gerne nochmal mit deinen Beispieldateien probieren

Ich wäre allgemein dafür einen Tooltip bei mouseover vom Ok Button einzublenden (zB "Löscht die gesamte Upload Queue").

**Comment by tobhu1981** [comment]
Da reicht es schon wenn du das GeoGebra Paket hochlädst. Das findest du hier: i:\EDV\Testcenter\GeoGebra.itcr.zip
