### ISSUE TITLE
GM: Anzeige Unit Seitenzahl testen

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#675]
**Version 15.3.0-alpha3**

Ursprünglicher Fehler:

Was bedeutet die 21 bei alias (siehe Bild) ![3](https://github.com/user-attachments/assets/169cd315-1e1d-4078-901b-54353047a248)

**Nochmal testen mit mehrseitigen Aspektaufgaben.**

**Comment by paflov** [comment]
Ich hab das quasi per Zufall mitgestet und kann das bestätigen. Werde es wahrscheinlich zur 15.4 hin fixen. Dürfte ne Kleinigkeit sein.
