### ISSUE TITLE
page_no wird falsch berechnet

### ISSUE THREAD

**Issue by nam-du-iqb** [iqb-berlin/testcenter#699]
## Ist:
Im Response Report wird in der Spalte "laststate" die page_no falsch berechnet. Es scheint, als ob die es einen string concat Fehler zu geben

Seite 2 ergibt Seite 11
Seite 3 ergibt Seite 21

## Soll:
Prüfen, dass der laststate richtig eingetragen wird. Sollte es sich um ein Player Problem handeln, dann weiterleiten.

## E2E-Test angelegt
* Wenn E2E-Test-Label angelegt, hier bestätigen, dass E2E-Tests angelegt wurden. Anschließend in Spalte: Freigabe Release verschieben mit neuer Zuweisung

**Comment by paflov** [comment]
Dublikat zu: https://github.com/iqb-berlin/testcenter/issues/675

Ist außerdem bereits im Verzweigungsbranch gefixed und kommt in der 15.4. Siehe anderes Ticket.
