### ISSUE TITLE
Adaptives Testen: Meldung beim Laden fehlerhaftes Booklet

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#701]
branch: fix/adaptivity-bugs

Im Element: `<value>` im Attribut: `from` kann sowohl die Unit-ID als auch die Alias-ID (falls Unit mehrfach verwendet wird) angegeben werden. Wird eine Unit-ID von einer Unit, die mehrfach verwendet wird, angegeben, hätte ich eine Fehlermeldung beim Laden erwartet, die besagt, dass die angegebene Unit-ID nicht eindeutig ist, da diese mehrfach vorkommt. Diese Meldung kommt aber beim Laden nicht, es wird erst später im Testverlauf eine Meldung generiert (Laden des Booklets).

**Comment by nam-du-iqb** [comment]
@tobhu1981 ein e2e test wäre gut. aber einfach nochmal prüfen, würde auch ausreichen

**Comment by tobhu1981** [comment]
@nam: wie meinst du das? Habt ihr an dem Problem gerabeitet und ich soll es einfach noch einmal ausprobieren? Oder sollen gezielt E2E-Test für dieses Szenario angelegt werden? Das wäre ziemlich aufwändig dieses Szenario in einem E2E-Test abzubilden.

**Comment by nam-du-iqb** [comment]
Ich habe mich missverständlich ausgedrückt. Die Änderungen sind noch nicht im Master, sondern im Branch 'fix/adaptivity-bugs'. Diesen müsstest du auschecken und nur händisch prüfen, ob das Problem so noch auftaucht

**Comment by tobhu1981** [comment]
Achso...alles klar. Habe es probiert. Nach dem Bauen sollte in Data/ws1 ein SAMPLE_BOOKLET2 liegen. Hier wird in `<Option>` bei `from` eine Unit-Id angegeben, die nicht eindeutig ist, weil diese Unit mehrfach im Booklet verwendet wird und nur über die Alias-Id eindeutig ist. Schon nach dem Bauen ist kein Fehlerhinweis bei dem Booklet im Arbeitsbereich "ws1" zu sehen. Auch wenn die Datei noch einmal geladen werden, erscheint keine Fehlermeldung.

**Comment by paflov** [comment]
Reicht der Unit-Test nicht, den ich mitgeliefert habe?

**Comment by tobhu1981** [comment]
Funktioniert in Branch: adaptivity-bugs
