### ISSUE TITLE
System-Check: ermittelte Internetgeschwindigkeit fehlerhaft

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#72]
IQB-Testcenter version 12.1.7@12.4.0

Der System-Check ermittel an meinem privaten Anschluss eine Download-Geschwindigkeit von: 26 Mbit/s.
Ich habe aber einen 50Mbit/s DSL-Anschluss. Bei Messungen über andere Anbieter, bspw. Ookla, wird mir dieser Wert auch in etwa ausgegeben.

**Comment by paflov** [comment]
Ich habe da echt mein Bestes gegeben damals, das gut zu ermitteln und hatte oft Übereinstimmungen mit anderen Anbietern und manchmal nicht. Das ist echt ne Wissenschaft für sich. Da laut MM die Zukunft des SysChecks ohnehin unbekannt ist, wird das hier bestimmt so bald nicht mehr angefasst. ich mach das Ticket daher mal zu.
