### ISSUE TITLE
GM: Anzeige verbleibende Zeit

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#722]
## Ist:

**Tippen auf Uhrsymbol in der Spalte "Abschnitt:**
Angezeigt wird: verbleibende Zeit: %s von %s Minute(n) 

## Soll:

% durch die Angabe der Minuten ersetzen oder ggf. löschen, da die verbleibende Zeit in dem grünen Kreis angezeigt wird. 

## Wo tritt der Fehler auf?
TC V15.3.4
iPad

**Comment by tobhu1981** [comment]
Hier ein Bild, wenn man mit der Maus auf die Uhr geht:<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBIQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b186e96fc2cca26fe519733d58dbaadeadb5bf8/Screenshot%20from%202024-12-05%2009-37-48.png" alt="Screenshot from 2024-12-05 09-37-48.png" />

**Comment by paflov** [comment]
Kann ich nicht sehen, aber ich habs inzwischen verstanden, danke :) Habs gefixed, ist mit dein dem aktuellen PR der in die 15.4 eingehen soll.

**Comment by tobhu1981** [comment]
Soll ich das nach dem PR nochmal prüfen oder können wir das Ticket sicher schließen? Ist ja eh nicht so nen wichtiger Punkt.

**Comment by paflov** [comment]
jo

**Comment by paflov** [comment]
wenns im master ist
