### ISSUE TITLE
GM: Optimierung bei "Springe zu" rückwärts

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#727]
## Ist:
enn versehentlich ein Block übersprungen wurde (z. B. bei doppeltem Antippen, s. o.) und dann versucht wird, in den "übersprungenen" Block zurückzuspringen, dann "gelingt" dies zwar bzw. eine Warnmeldung für den Block erscheint (Zeit abgelaufen); man kann dann aber auch nicht mehr zu dem Block springen, aus dem man versucht hat "zurückzuspringen"

## Soll:
Ein "Springe zu" in vorherige, zeitlich begrenzte Blöcke grundsätzlich nicht erlauben? --> bringt sowieso nichts, da der Block nicht mehr betreten werden kann und man sich auf diesem Wege nicht auch den aktuellen Block zerschießt. 

## Wo tritt der Fehler auf?
TC V15.3.4
Samsung/iPad Tablets

**Comment by paflov** [comment]
Verstehe ich ehrlich gesagt nicht.
