### ISSUE TITLE
GM: Filter speichern erst nach erneuter Spaltenauswahl möglich

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#735]
## IST:
Wird ein neuer Filter angelegt und wird die Vorauswahl in der ersten Auswahlliste ganz oben so belassen, kann nach Angabe der restlichen Felder: Filtertyp und Filter nicht gepseichert werden. Der Speicherbutton wird erst aktiv nachdem in der oberen Liste eine andere Spalte gewählt wird und anschließend noch einmal die Spalte, die bereits in der Vorauswahl stand, ausgewählt wird. Alternativ kann der erweiterte Modus aktiviert werden, alle dortigen Felder ausgefüllt werden, dann wird der Button auch aktiv.

## SOLL:
Speicher-Button muss auch aktiv werden, wenn Vorauswahl in erstem Listenfeld nicht geändert wird.

**Comment by tobhu1981** [comment]
@Philipp: Hast du das schon behoben in der 15.4.0-beta aus S3? Kann das nämlich nicht mehr reproduzieren.

**Comment by paflov** [comment]
Ja ich denke ja, als ich die zusätzlichen Funktionen eingebaut habe. Oder noch früher vom Sprung der 15.3.0-alpha auf die 15.3.0.
