### ISSUE TITLE
Eingabefeld Freigabewort für Kinder intuitiver gestalten 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/testcenter#74]
Eine Verbesserung ist gewünscht, die keine komplett neue Funktionalität darstellt, aber auch ein Fehlverhalten im engeren Sinne beschreibt.

* Optische Verbesserung

![grafik](https://user-images.githubusercontent.com/78726636/174800408-178c41c5-6c30-4a01-a338-ba6f2b2578a6.png)

bzgl. des Feldes für das Freigabewort: in der Pilotierung haben die Kinder teils nicht gecheckt, dass man da was eintragen kann, also das Passwort. Dieses andere Eingabefeld (Linie mit Vorbelegung) wurde nicht als solches erkannt.

Vorschlag:
Vorbelegung (im Beispiel Screenshot das 2. mal "Aufgaben Probeumsetzung") im Eingabefeld weglassen 
Eingabefeld nicht nur als Linie, sondern als Feld layouten (im Editor nennt sich diese Ansicht "umrandet")

**Comment by paflov** [comment]
Hier wäre zu diskutieren, ob man generell alle Eingabefelder (also auch beim Login) derartig umgestalten sollte.

**Comment by paflov** [comment]
Nach Klärung mit tJK und PK: Alle Eingabefelder (auch login) umgetstalten in Boxen.

**Comment by paflov** [comment]
Die gleichen Material Settings verwenden, wie im Aspect am Besten.

**Comment by paflov** [comment]
Betrifft: TestController und Login
