### ISSUE TITLE
Booklets werden doppelt angezeigt

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/testcenter#754]
# Fehlerbeschreibung

Beim Login nur mit Username per URL wird für einen Login zweimal das gleiche Booklet zur Auswahl angezeigt, obwohl in der Testtaker Datei nur ein Booklet konfiguriert ist. Erwartetes Verhalten wäre, dass der Link direkt in den Test führt. Bei anderen Logins aus der gleichen Testtaker Datei funktioniert dies, nur bei run_pyv65 tritt das Verhalten auf.

![Bildschirmfoto vom 2024-11-27 15-50-48](https://github.com/user-attachments/assets/0e619883-8337-4f9c-a502-6da44ab41df6)

# Kontext
**Server**: Docker Production

**Testcenter-Version**: 15.3.4

**Testtaker-Datei**: [testtakers-15.xml.txt](https://github.com/user-attachments/files/17936197/testtakers-15.xml.txt) (txt wegen Github Beschränkung angehängt)

**Browser**: Firefox

**Comment by nam-du-iqb** [comment]
Scheint nicht an der Testtakers Datei zu liegen. Konnte bei Übernahme des Logins diesen Fehler nicht reproduzieren. @ojauch , liegt dieses Beispiel auf einem der IQB Server oder lokal bei dir?

**Comment by ojauch** [comment]
@nam-du-iqb Der Fehler ist bei mir in einer Installation auf einem unserer Server aufgetreten
