### ISSUE TITLE
"Allgemeines Server-Problem" nach dem Hochladen einer aktualisierten tt-Datei

### ISSUE THREAD

**Issue by larapohle** [iqb-berlin/testcenter#766]
**Achtung, Silke hat morgen die Präpilotierung - bitte nichts aus dem Arbeitsbereich entfernen (immerhin funktioniert es jetzt)**

**Nachstellen**
1. Ich habe eine Unit im Arbeitsbereich "BiSta Präpilotierung Markierfunktion" (TC2) ergänzt und auch die tt-Datei nach Anpassungen neu hochgeladen. Ich hatte die Group id und das Label neu vergeben:  <Group id="Pilot_Markieren" label="Pilot_Markieren"> 
Der Grund für die Umbenennung war der, dass ich entdeckt hatte, dass id und label nicht mehr so hießen wie urspünglich von mir benannt (jeweils Präpilot_Markieren) --> ich habe die tt-Datei in der Zwischenzeit aber wirklich nicht angefasst; in den abgezogenen Daten ist auch noch der ursprüngliche von mir vergebene groupname gewesen.
2. Das Hochladen der Dateien hat einwandfrei funktioniert, allerdings konnte ich mich anschließend nicht mit dem Anmeldenamen einloggen. Es erschien eine Fehlermeldung (s. Screenshot/Bugreport).
3. Philipp Franikowski hat sich dann eingeschaltet und ebenfalls diverse Varianten (auch zufällige IDs) ausprobiert, aber es wurde nichts mehr akzeptiert, was nicht dem Default der Group id entsprach. Das Label hingegen konnte umbenannt werden. 

**Screenshots, Links, erschienene Fehlermeldungen**
<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRYQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bd9a8e09dca3a8a02ce376c27eb1d73cfe71518/grafik.png" alt="grafik.png" />

**Und hier ist der Bug-Report: Fehlerbericht: Allgemeines Server-Problem.**

Could not retrieve group token for `Test`.

Http failure response for https://iqb-testcenter2.de/api/session/login: 500 OK

Error-Id: error-675867d2474710.11435038

Zeitpunkt: Dec 10, 2024, 5:09:54 PM

Url: https://iqb-testcenter2.de/#/r/login/

Browser: Chrome 131.0.0.0

Betriebssystem: Windows 10

Gerät:

**Comment by tobhu1981** [comment]
Nachvollziehbar. Das passiert wenn die TT-XML verändert wird, der bestehende Antwortdatensatz aber nicht gelöscht wird. Der Test wurde ja bereits ein- oder mehrfach gestartet, es wurden Antwortdaten und entsprechende Token generiert. Wenn ihr eine zusätzliche Group mit dem gewünschten Namen angelegt hättet, wäre das gegangen. Genauso wenn zuvor der bestehende Antwortendatensatz gelöscht wurden wäre.

**Comment by franikowsp** [comment]
Wir haben dann aber auch den bestehenden Datensatz gelöscht und das Problem persistiert trotzdem - es sind trotzdem **keine anderen** als die zuvor eingestellten Group-IDs mehr zulässig. (Gerade können wir nicht ran, aber wenn wir die Daten abgezogen haben, können wir den Workspace wieder freigeben).

**Comment by paflov** [comment]
Hmmm, das müssen wir wohl "vor Ort" ausprobieren, sobald wir können. Vielleicht interferiert auch eine andere TT-Datei auf einem anderen Workspace oder so.

**Comment by tobhu1981** [comment]
Hmm...komisch, habe es gerade auf S4 (gleiche TC-Version wie TC2) mit den von euch verwendeten Daten probiert. Hier konnte ich die Group-Id nach Löschen der Antworten verändern und habe den Fehler nur bekommen, wenn ich diesen zuvor nicht gelöscht habe. @Philipp Frank: Hast du noch eine Idee, wie so etwas noch zu erklären wäre? DB-Satz nicht richtig bereinigt etc.?

**Comment by franikowsp** [comment]
Hatte ich auch vermutet, aber der String, den ich eingesetzt hatte, ist so zufällig gewesen, dass es sehr unwahrscheinlich ist, dass der nochmal auf der 2 auftaucht. Das TC warnt ja sonst eigentlich auch, wenn die Gruppe vergeben ist. 🤔

**Comment by paflov** [comment]
Naja ich meinte schon wie auch immer geartetes Bug-Verhalten, dass aber als zusätzlichen Auslöser eine TT-Datei auf einem anderen Workspace hat. Das klären wir schon, wenn wir daran kommen.

**Comment by franikowsp** [comment]
Wir haben die Behebung durchgeführt und die Daten lokal gesichert. Ihr könntet jetzt ran aus unserer Sicht.

**Comment by tobhu1981** [comment]
Ich habe es gerade probiert und konnte nach löschen der Antworten problemlos die bestehende Group: "TestTakerGroup_h3x4a3z" umbenennen und mich anschließend mit dem Login und einem Code dieser Gruppe anmelden. Was auch immer da gestern los, es wird wohl schwierig das zu reproduzieren.

**Comment by franikowsp** [comment]
Ich kann es, glaube ich, so reproduzieren:

1. Vollständig anlegen, dann einmal als Testtaker durchklicken mit alter ID. Daten drin behalten!
2. Nun den Testtaker-File austauschen (ohne die Daten gelöscht zu haben; nur ID ändern)
3. Nochmal versuchen, einzuloggen - ab jetzt tritt der Fehler auf.
4. Auch wenn man jetzt die Daten als Admin löscht und sich dann nochmal anzumelden versucht, geht es nicht mehr.

**Comment by tobhu1981** [comment]
Das kann ich so bestätigen. Hatte es gestern auch so auf S4 probiert, da gab es das Problem so nicht obwohl gleiche Version. @paflov: Schaust du mal drauf bei Gelegenheit?

**Comment by paflov** [comment]
Kann es reproduzieren. Ist gar nicht so geheimnisvoll. Auch nicht neu, muss seit Einführung des File-Service bestehen. Werde ich fixen.

**Comment by paflov** [comment]
Eine Sache ist aber klarzustellen: Das erwartete Verhalten ist, dass man sich einloggt und eine NEUE Session bekommt. Die alte besteht als Datensatz weiter, aber kann nicht mehr eingeloggt werden.

**Comment by franikowsp** [comment]
> Eine Sache ist aber klarzustellen: Das erwartete Verhalten ist, dass man sich einloggt und eine NEUE Session bekommt. Die alte besteht als Datensatz weiter, aber kann nicht mehr eingeloggt werden.

Ja, das macht Sinn. Was würde aber passieren, wenn man erst eine XML mit einer anderen ID reinlädt und dann doch wieder die alte? Würde die Session dann doch fortbestehen?

**Comment by paflov** [comment]
@franikowsp So dachte ich. Aber tatsächlich habe ich gerade eine Lösung gefunden wie es die selbe Session bleibt und die Gruppen-ID sich verändert. Das ist sicherlich intuitiv logischer und hat den netten Nebeneffekt, das man Sessions durch re-upload  in neue Gruppen "verschieben" kann. Das könnte sich noch als nützlich erweisen.

**Comment by paflov** [comment]
Gab übrigens schon ein Ticket dazu: #637
