### ISSUE TITLE
Festhängen auf Seite "Schülercode eingeben"

### ISSUE THREAD

**Issue by larapohle** [iqb-berlin/testcenter#767]
**Nochmal Achtung (zur Sicherheit): Bitte nichts aus dem TC-Arbeitsbereich "BiSta Präpilotierung Markierfunktion" (TC2) entfernen, da morgen Silkes Erprobung in der Schule ist und aktuell alles funktioniert**

Zum Nachstellen: 
1. Öffne https://iqb-testcenter2.de/#/y4r6d5t 
2. Auch wenn ich anschließend https://iqb-testcenter2.de/#/r/login/ in die Browserleiste eingebe oder auf da IQB-Icon klicke, bleibe ich hier: https://iqb-testcenter2.de/#/r/code-input
3. Nur über "Neu anmelden" komme ich aus der Seite raus oder indem ich den Browserverlauf lösche. 

Das Verhalten tritt auch dann auf, wenn ich nicht direkt dem Link folge, sondern den Anmeldenamen manuell eingebe. 

Ich bin mir nicht 100 % sicher, ob es ein Bug ist, aber ich meine, dass das vorher nicht so war.

**Comment by tobhu1981** [comment]
Habe ich Tatsache noch nie probiert und kann daher nicht sagen ob das ein neues Verhalten ist. Zumindest in der 15.2 verhält es sich genauso. Das TC2 läuft aktuell mit 15.3.4. Ihr könnt das sicherlich besser einschätzen, aber ich wüsste jetzt auch nicht direkt warum das ein Problem ist, denn mit dem Schalter "Neu anmelden" kommt man ja wieder raus.

**Comment by paflov** [comment]
Mir ist auch nicht ganz klar inwiefern das ein Fehlverhalten sein soll. Mitten in der zweistufigen Anmeldung darf man nicht herausnavigieren, sondern entweder die Anmeldung abschließen oder abbrechen. Könnte sein, dass es vorher anders war, dann war es vorher aber buggy. Es gab in dem Bereich einen Bug, den wir gefixed haben, dadurch kann dieses hier mit repariert worden sein.
