### ISSUE TITLE
GM: Wording Schaltflächen überarbeiten

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#770]
Springe zu ("Block") --> Starte ("Block")

Pause --> Test pausieren

Weiter --> Test fortsetzen

**Comment by paflov** [comment]
Warum nicht einfach customTexts verwenden?

**Comment by tobhu1981** [comment]
Ja warum eigentlich nicht? Weil ich da nicht rein geschaut habe:(
