### ISSUE TITLE
bytes pipe gibt null aus für negative Werte

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#79]
gibt null aus, wenn man negative werte reinwirft

**Comment by huaning-yang** [comment]
Was wäre denn hier das gewünschte Ergebnis?
Sollen die negativen Werte erhalten bleiben oder eine Fehlermeldung zurückgegeben werden?

**Comment by huaning-yang** [comment]
@paflov sollen die negativen Werte erhalten bleiben oder eine Fehlermeldung geworfen werden?
Ich weiß nur nicht wann man negative Bytes haben würde, deswegen frage ich

**Comment by huaning-yang** [comment]
Nach unserer letzten Unterhaltung wurde ersichtlich, dass das nicht benötigt wird.
Schließe das dann jetzt erst mal.
