### ISSUE TITLE
Secure Client Initated Renegotiation möglich

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#80]
> Durch    wiederholtes    und    fortwährendes    Ausführen    der    Client-Initiated Renegotiation kann, aufgrund der für die Aushandlung nötigen Ressourcen, der Server möglicherweise überlastet und somit ein Denial-of-Service hervorgerufen werden.

> Die TLS-Renegotiation sollte nach Möglichkeit vollständig deaktiviert werden. Ist dies  nicht  möglich,  so  sollte  die  Anzahl  der  ausgeführten  TLS-Renegotiations überwacht und beschränkt werden.

@see: https://blog.qualys.com/product-tech/2011/10/31/tls-renegotiation-and-denial-of-service-attacks

**Comment by rhenck** [comment]
Kann hier keine Probleme festellen. Datenpunkte folgen.

- Habe selber nochmal getestet über das Tool, welches im Report verwendet wird. Einmal für unseren Server und dann auch noch für den Baden-Würtemberger. Bei beiden ist Client Initated Renegotiation nicht aktiv:
https://www.ssllabs.com/ssltest/analyze.html?d=iqb-testcenter.de&hideResults=on

![image](https://user-images.githubusercontent.com/446878/212925131-1526fc32-a227-4e7c-9fbd-caaf801a9b2b.png)

**Comment by rhenck** [comment]
Recherchen zu Apache2 und Traefik ergaben, dass bei das standardmäßig nicht erlauben (Traefik kann das garnicht) und ich kann auch nix finden, dass wr das irgendwo explizit angeschaltet hätten.

https://github.com/traefik/traefik/issues/7643
"It's indeed not configurable. But the default configuration for the TCP server is currently to not allow renegotiation support."

https://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslinsecurerenegotiation
"If [mod_ssl](https://httpd.apache.org/docs/2.2/mod/mod_ssl.html) is linked against OpenSSL version 0.9.8m or later, by default renegotiation is only supported with clients supporting the new protocol extension."


Habe außerdem noch manuell gecheckt:
openssl s_client  -connect iqb-testcenter.de:443

Resultat (stark gekürzt):
"Secure Renegotiation IS NOT supported"

**Comment by paflov** [comment]
Dann hat sich das wohl erledigt. Wer weiß, das war ja noch TC 12, eventuell durch die ganzen updates der container? Ist doch wunderbar.
