### ISSUE TITLE
Implement stateReportPolicy="on-demand"

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#84]
Bisher wurde nur der stateReportPolicy-modus implementiert.
"on-demand" steht zwar in der Spezifikation (https://verona-interfaces.github.io/player/#operation-publish-vopStartCommand),
und wird von den wesentlichen Playern (aspcet, simple) unterstützt, aber nicht vom testcenter.
Dazu wäre zu klären, wann das Testcenter denn fragen soll.

Außerdem ist unklar was mit stateReportPolicy="none" gemeint ist.

**Comment by mechtelm** [comment]
Version 5 der Player-Spec hat vopGetStateRequest entfernt.
