### ISSUE TITLE
Änderung Text Sammel-Fehlermeldung

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter#88]
Hier ging es um die Sammelfehlermeldung: "Es ist ein schwerer Fehler aufgetreten.......". Aus BW kam die Meldung, dass diese Meldung die Lehrkräfte nervös macht. Diese rufen dann ganz aufgeregt beim IBBW an und das IBBW kann nicht viel sagen, weil eine Vielzahl von Fehlern infrage kommen. Soweit ich dich verstanden habe, ist das für dich nur eine Meldung damit du ungefähr mögliche Fehlerursachen eingrenzen kannst und es gibt wohl keine Möglichkeit alle infrage kommenden Fehler noch einmal mit separaten Meldungen zu versehen. Vielleicht könnte man die Meldung zumindest umbenennen in: Es ist ein technischer Fehler aufgetreten. Bitte rufe deine Lehrkraft und starte mit ihrer Unterstützung den Test neu. Was hälst du davon?

**Comment by paflov** [comment]
Das Erscheinunsbild der Fehlermeldungen sollten wir im Zusammenhang mit der geplanten Fehler-Melden Funktion noch einmal diskutieren.

**Comment by paflov** [comment]
Neue Texte liegen vor und müsse eingepflegt werden.
