### ISSUE TITLE
Fokus Lost Zeit loggen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter#96]
Vorschlag Kollegen Test 8.9: Sollte man die Zeit loggen, die jemand den Fokus verloren hat.

Man müsste also einen Timer laufen lassen auf der Pause Seite und diese Zeil als Teststate ins Backend loggen z. B. as BookletState.FOCUS_LOST_TIME. 

Prüfen ob das mit mäßigem Aufwand machbar.

**Comment by mechtelm** [comment]
Ja. Die Entscheidung, ob die Person aus dem Sample entfernt wird wegen Bedenken bzgl Antwortqualität, wird erst später bei der Auswertung gefällt.
